package farray.json

import farray.Fuse

/** Entry point for the fused JSON projection parser.
  *
  * `Json.ndjson[Rec](bytes).stream.filter(_.amount > 18).map(_.category).toList` compiles to ONE per-record byte scanner driven by the EXISTING `fuse`
  * optimizer: only the fields the pipeline reads are scanned (projection pushdown / dead-column elimination), a predicate field is decoded first and the record
  * is abandoned at the byte level if it fails (predicate pushdown), a projected string is decoded LAZILY only for survivors (compute-for-survivors), and no
  * per-record object is allocated for reduce/project pipelines.
  *
  * The byte-level details (key dispatch by raw byte compare, value skipping, SWAR string scan, allocation-free number parsing) are GENERATED by the macro and
  * hidden behind this surface — the user writes the same `.filter().map().<terminal>` pipeline they would over an in-memory `FArray`, started with `.stream`.
  *
  * Scope (v1): flat case-class records with Int/Long/Double/String fields, compact one-line-per-record NDJSON in an in-memory buffer; the `filter`/`map` stages
  * and the field-reading terminals (`sum`/`fold`/`reduce`/ `agg`/`toList`/`count`/`foreach`/`find`/`exists`/`forall`/`indexWhere`). Nested objects/arrays,
  * streaming chunk sources, and `zip`/`flatMap`/`collect`/`takeWhile`/`distinct` over the JSON source are not yet supported (a clear compile error if used).
  */
final class NdjsonSource[T](
    private[farray] val buf: Array[Byte],
    private[farray] val from: Int,
    private[farray] val until: Int
):
  /** Start the fused pipeline over this source. Named `stream` (not `fuse`) to signal at the call site that the data is a byte SOURCE consumed record-by-record
    * — `Json.ndjson[T](bytes).stream.filter(…).map(…)` — not an in-memory `FArray` (which uses `.fuse`). The macro reads `T`'s fields + the downstream
    * `filter`/`map` accesses and generates the per-record projection scanner.
    */
  inline def stream: Fuse[T] = new Fuse[T](this)

  /** alias for `stream` (the in-memory verb), for readers who already know `.fuse`. */
  inline def fuse: Fuse[T] = new Fuse[T](this)

object Json:
  /** wrap an in-memory NDJSON byte buffer as a projectable SOURCE of `T` records — start a pipeline with `.stream`:
    * `Json.ndjson[T](bytes).stream.filter(…).map(…).<terminal>`.
    */
  inline def ndjson[T](bytes: Array[Byte]): NdjsonSource[T] = new NdjsonSource[T](bytes, 0, bytes.length)
  inline def ndjson[T](bytes: Array[Byte], from: Int, until: Int): NdjsonSource[T] =
    new NdjsonSource[T](bytes, from, until)
