package farray.json

import farray.{Fuse, ByteRecordSource}

/** Entry point for the fused JSON projection parser.
  *
  * `Json.ndjson[Rec](bytes).stream.filter(_.amount > 18).map(_.category).toList` compiles to ONE per-record byte scanner driven by the EXISTING `fuse`
  * optimizer: only the fields the pipeline reads are scanned (projection pushdown / dead-column elimination), a predicate field is decoded first and the record
  * is abandoned at the byte level if it fails (predicate pushdown), a projected string is decoded LAZILY only for survivors (compute-for-survivors), and no
  * per-record object is allocated for reduce/project pipelines.
  *
  * The byte-level details (key dispatch by raw byte compare, value skipping, SWAR string scan, allocation-free number parsing) are GENERATED by the macro and
  * hidden behind this surface — the user writes the same `.filter().map().<terminal>` pipeline they would over an in-memory `FArray`, started with `.stream`.
  *
  * Scope (v1): flat case-class records with Int/Long/Double/String fields, compact one-line-per-record NDJSON, EITHER in an in-memory buffer (`Json.ndjson`) OR
  * streamed in constant memory from an `InputStream`/file (`Json.ndjsonStream`/`ndjsonFile` — same scanner, records straddling block boundaries stitched by the
  * framer); the `filter`/`map` stages and the field-reading terminals (`sum`/`fold`/`reduce`/ `agg`/`toList`/`count`/`foreach`/`find`/`exists`/`forall`/
  * `indexWhere`). Nested objects/arrays and `zip`/`flatMap`/`collect`/`takeWhile`/`distinct` over the JSON source are not yet supported (a clear compile
  * error).
  */
final class NdjsonSource[T](
    private val backing: Array[Byte],
    private val from: Int,
    private val until: Int
) extends ByteRecordSource:
  /** Start the fused pipeline over this source. Named `stream` (not `fuse`) to signal at the call site that the data is a byte SOURCE consumed record-by-record
    * — `Json.ndjson[T](bytes).stream.filter(…).map(…)` — not an in-memory `FArray` (which uses `.fuse`). The macro reads `T`'s fields + the downstream
    * `filter`/`map` accesses and generates the per-record projection scanner.
    */
  inline def stream: Fuse[T] = new Fuse[T](this)

  /** alias for `stream` (the in-memory verb), for readers who already know `.fuse`. */
  inline def fuse: Fuse[T] = new Fuse[T](this)

  // ── ByteRecordSource: the in-memory case is the trivial one-chunk framer. The whole buffer IS the one chunk;
  //    `nextRecord` walks newline-framed records from `from` to `until`. No carry buffer, no Partial — every record
  //    is already complete and contiguous. This is the parity anchor for the extraction (zero behaviour change).
  private var chunkServed: Boolean = false
  private var cursor: Int = from // start of the NEXT record to frame
  private var recStart: Int = from
  private var recEnd: Int = from
  // ── ByteRecordSource contract (the only public surface) ──
  def buf: Array[Byte] = backing
  def recordStart: Int = recStart
  def recordEnd: Int = recEnd
  def nextChunk(): Boolean =
    if chunkServed then false
    else { chunkServed = true; cursor = from; true }
  def nextRecord(): Boolean =
    if cursor >= until then false
    else
      recStart = cursor
      var e = cursor
      while e < until && backing(e) != '\n' do e += 1
      recEnd = e // exclusive end at the '\n' (or `until`)
      cursor = e + 1 // skip the '\n' for the next record
      true

/** A STREAMING NDJSON source: constant-memory projection over an arbitrarily large byte stream (an `InputStream` / file), reusing the SAME decomposed scan-pass
  * as the in-memory [[NdjsonSource]] — only the framing differs. The [[Framer]] underneath owns the block reads + boundary stitch ("unfinished record"); the
  * macro sees only complete records and emits the identical projection-pushdown scanner. `T` is the (phantom) record case class the macro reads its fields off;
  * the runtime carries no `T`.
  */
final class StreamingNdjsonSource[T](read: (Array[Byte], Int, Int) => Int, blockSize: Int, doClose: () => Unit) extends Framer(read, blockSize, doClose):
  inline def stream: Fuse[T] = new Fuse[T](this)
  inline def fuse: Fuse[T] = new Fuse[T](this)

object Json:
  /** wrap an in-memory NDJSON byte buffer as a projectable SOURCE of `T` records — start a pipeline with `.stream`:
    * `Json.ndjson[T](bytes).stream.filter(…).map(…).<terminal>`.
    */
  inline def ndjson[T](bytes: Array[Byte]): NdjsonSource[T] = new NdjsonSource[T](bytes, 0, bytes.length)
  inline def ndjson[T](bytes: Array[Byte], from: Int, until: Int): NdjsonSource[T] =
    new NdjsonSource[T](bytes, from, until)

  /** the default streaming block size — a fresh `read()` worth of bytes per refill; the working buffer is this plus room for one straddling record. 64 KiB
    * matches a typical filesystem/socket read.
    */
  inline val DefaultBlockSize = 65536

  /** Stream NDJSON records of `T` from an `InputStream` in CONSTANT MEMORY (O(block + largest record)) — the decomposed projection scanner runs per record
    * exactly as in-memory, but the bytes are pulled lazily and records straddling block boundaries are stitched by the framer. The stream is OWNED: `close()`
    * closes it (on exhaustion, short-circuit, OR exception — the fused driver wraps the loop in try/finally). Example:
    * {{{Json.ndjsonStream[Rec](Files.newInputStream(path)).stream.filter(_.amount > 18).map(_.category).toList}}}
    */
  def ndjsonStream[T](in: java.io.InputStream, blockSize: Int = DefaultBlockSize): StreamingNdjsonSource[T] =
    new StreamingNdjsonSource[T]((b, off, max) => in.read(b, off, max), blockSize, () => in.close())

  /** Stream NDJSON records of `T` from a file (opened lazily on the first read, owned + closed). Constant memory. */
  def ndjsonFile[T](path: java.nio.file.Path, blockSize: Int = DefaultBlockSize): StreamingNdjsonSource[T] =
    // open lazily so construction is cheap / side-effect-free; the first `read` triggers the open.
    var in: java.io.InputStream = null
    def ensure(): java.io.InputStream =
      if in == null then in = java.nio.file.Files.newInputStream(path)
      in
    new StreamingNdjsonSource[T]((b, off, max) => ensure().read(b, off, max), blockSize, () => if in != null then in.close())
