package farray.json

import farray.Fuse

/** Entry point for the fused JSON projection demo.
 *
 *  `Json.ndjson[Rec](bytes).fuse.filter(_.amount > 18).map(_.category).toList` compiles to ONE per-record
 *  byte scanner driven by the EXISTING `fuse` optimizer: only the fields the pipeline reads are scanned
 *  (projection pushdown / dead-column elimination), a predicate field is decoded first and the record is
 *  abandoned at the byte level if it fails (predicate pushdown), a projected string is decoded LAZILY only
 *  for survivors (compute-for-survivors), and no per-record object is allocated for reduce/project pipelines.
 *
 *  The byte-level details (key dispatch by raw byte compare, value skipping, SWAR string scan, allocation-free
 *  number parsing) are GENERATED by the macro and hidden behind this surface — the user writes the same
 *  `.fuse.filter().map().<terminal>` pipeline they would over an in-memory `FArray`.
 *
 *  Scope (v1, the demo): flat case-class records with Int/Long/Double/String fields, compact one-line-per-record
 *  NDJSON in an in-memory buffer, the `filter`/`map` stages and the `sum`/`fold`/`toList`/`count`/`foreach`
 *  terminals. Nested objects/arrays, streaming chunk sources, and `zip`/`flatMap` over the JSON source are not
 *  yet supported (a clear compile error if used). */
final class NdjsonSource[T](
    private[farray] val buf: Array[Byte],
    private[farray] val from: Int,
    private[farray] val until: Int
):
  /** start the fused pipeline. The macro reads `T`'s fields + the downstream `filter`/`map` accesses and
   *  generates the projection scanner. */
  inline def fuse: Fuse[T] = new Fuse[T](this)

object Json:
  /** wrap an in-memory NDJSON byte buffer as a projectable source of `T` records. */
  inline def ndjson[T](bytes: Array[Byte]): NdjsonSource[T] = new NdjsonSource[T](bytes, 0, bytes.length)
  inline def ndjson[T](bytes: Array[Byte], from: Int, until: Int): NdjsonSource[T] =
    new NdjsonSource[T](bytes, from, until)
