package farray

import bleep.*
import bleep.internal.FileUtils

import java.nio.file.Files

/**
 * Generates the sealed FArray core hierarchy: `FBase` (abstract storage-shuffling API + a concrete
 * O(1) `concat` that builds a `Concat` tree node) + one `<Name>Arr` leaf per primitive + the
 * `Object[]`-backed `RefArr` leaf + the `Concat` tree node. Wired as `farray`'s sourcegen.
 *
 * Element-touching combinators and element-insert ops (`:+`/`+:`/`updated`) live in Scala (inline,
 * specialized) — NOT here. Adding a primitive = one row in `prims`.
 */
object GenCores extends BleepCodegenScript("GenCores") {

  final case class Prim(name: String, jt: String, boxed: String)

  val prims: List[Prim] = List(
    Prim("Int", "int", "Integer"),
    Prim("Long", "long", "Long"),
    Prim("Double", "double", "Double"),
    Prim("Float", "float", "Float"),
    Prim("Short", "short", "Short"),
    Prim("Byte", "byte", "Byte"),
    Prim("Char", "char", "Character"),
    Prim("Boolean", "boolean", "Boolean")
  )

  override def run(started: Started, commands: Commands, targets: List[GenCores.Target], args: List[String]): Unit =
    targets.foreach { target =>
      val dir = target.sources.resolve("farray")
      FileUtils.deleteDirectory(target.sources)
      Files.createDirectories(dir)
      Files.writeString(dir.resolve("FBase.java"), fbase)
      Files.writeString(dir.resolve("RefArr.java"), refArr)
      Files.writeString(dir.resolve("RefAppend.java"), refUnary("Append"))
      Files.writeString(dir.resolve("RefPrepend.java"), refUnary("Prepend"))
      Files.writeString(dir.resolve("Concat.java"), concat)
      Files.writeString(dir.resolve("RangeNode.java"), rangeNode)
      Files.writeString(dir.resolve("ReverseNode.java"), reverseNode)
      prims.foreach { p =>
        Files.writeString(dir.resolve(s"${p.name}Arr.java"), primCore(p))
        Files.writeString(dir.resolve(s"${p.name}Append.java"), primAppend(p))
        Files.writeString(dir.resolve(s"${p.name}Prepend.java"), primPrepend(p))
      }
      Files.writeString(dir.resolve("Repr.scala"), reprSrc)
      Files.writeString(dir.resolve("FArrayOps.scala"), farrayOps)
    }

  /** Unified array-representation evidence — subsumes primitive specialization, value-class/opaque
   *  unwrapping (Prim + inline wrap/unwrap), and reference ClassTag (RefRepr.ct). One per concrete A;
   *  absent for abstract A ⇒ summonFrom fails ⇒ compile error (specialize-or-fail). */
  private def reprSrc: String = {
    val subtraits = opKinds.map { k =>
      if k.name == "Ref" then "trait RefRepr[A] extends Repr[A] { type Prim = A; def ct: scala.reflect.ClassTag[A] }"
      else s"trait ${k.name}Repr[A] extends Repr[A] { type Prim = ${k.arr} }"
    }.mkString("\n")
    val givens = opKinds.map { k =>
      if k.name == "Ref" then
        "  given refRepr[A <: AnyRef](using c: scala.reflect.ClassTag[A]): RefRepr[A] with { def ct: scala.reflect.ClassTag[A] = c; inline def unwrap(a: A): A = a; inline def wrap(p: A): A = p }"
      else
        s"  given ${k.lc}Repr: ${k.name}Repr[${k.arr}] with { inline def unwrap(a: ${k.arr}): ${k.arr} = a; inline def wrap(p: ${k.arr}): ${k.arr} = p }"
    }.mkString("\n")
    s"""package farray
       |
       |// GENERATED by GenCores — do not edit.
       |sealed trait Repr[A] {
       |  type Prim
       |  inline def unwrap(a: A): Prim
       |  inline def wrap(p: Prim): A
       |}
       |$subtraits
       |
       |object Repr {
       |$givens
       |}
       |""".stripMargin
  }

  // ===== generated per-kind Scala combinators (the read×write matrix lives here, not hand-written) =====

  /** name=core prefix (Int/Long/Double/Ref); arr=Scala array elem type; pat=erasedValue pattern; dflt=zero. */
  final case class Kind(name: String, arr: String, pat: String, dflt: String) { def lc = name.toLowerCase }

  // Start with the common numeric kinds + reference; add rows here to cover more primitives.
  val opKinds: List[Kind] = List(
    Kind("Int", "Int", "Int", "0"),
    Kind("Long", "Long", "Long", "0L"),
    Kind("Double", "Double", "Double", "0.0"),
    Kind("Ref", "Object", "AnyRef", "null")
  )

  private val grow =
    "if (sp + 2 > stack.length) { val ns = stack.length * 2; stack = java.util.Arrays.copyOf(stack, ns); tail = java.util.Arrays.copyOf(tail, ns); isTail = java.util.Arrays.copyOf(isTail, ns) }"

  private def dfsDef(k: Kind): String = {
    // Lazy nodes emit unboxed via <kind>At per element (RangeNode is closed-form, Int only). onOne/At
    // return the raw primitive, so no boxing — only the boxed `applyBoxed` path (iterator) ever boxes.
    val rngCase = if k.name == "Int" then "\n       |        case rng: RangeNode => { val rn = rng.length; var ri = 0; while (ri < rn) { onOne(rng.start + ri * rng.step); ri += 1 } }" else ""
    s"""  inline def dfs${k.name}(root: FBase)(inline onLeaf: (Array[${k.arr}], Int) => Unit)(inline onOne: ${k.arr} => Unit): Unit = {
       |    var stack = new Array[FBase](16); var tail = new Array[${k.arr}](16); var isTail = new Array[Boolean](16)
       |    stack(0) = root; var sp = 1
       |    while (sp > 0) {
       |      sp -= 1
       |      if (isTail(sp)) onOne(tail(sp))
       |      else stack(sp) match {
       |        case leaf: ${k.name}Arr => onLeaf(leaf.arr, leaf.length)
       |        case p: ${k.name}Prepend => { onOne(p.elem); $grow; stack(sp) = p.base; isTail(sp) = false; sp += 1 }
       |        case a: ${k.name}Append => { $grow; tail(sp) = a.elem; isTail(sp) = true; sp += 1; stack(sp) = a.base; isTail(sp) = false; sp += 1 }
       |        case c: Concat => { $grow; stack(sp) = c.right; isTail(sp) = false; sp += 1; stack(sp) = c.left; isTail(sp) = false; sp += 1 }
       |        case rev: ReverseNode => { val rn = rev.length; var ri = 0; while (ri < rn) { onOne(${k.lc}At(rev.base, rn - 1 - ri)); ri += 1 } }$rngCase
       |        case _ => ()
       |      }
       |    }
       |  }""".stripMargin
  }

  private def atDef(k: Kind): String = {
    val rngCase = if k.name == "Int" then "\n       |    case rng: RangeNode => rng.start + i * rng.step" else ""
    s"""  def ${k.lc}At(node: FBase, i: Int): ${k.arr} = node match {
       |    case leaf: ${k.name}Arr => leaf.arr(i)
       |    case c: Concat => if (i < c.left.length) ${k.lc}At(c.left, i) else ${k.lc}At(c.right, i - c.left.length)
       |    case a: ${k.name}Append => if (i < a.base.length) ${k.lc}At(a.base, i) else a.elem
       |    case p: ${k.name}Prepend => if (i == 0) p.elem else ${k.lc}At(p.base, i - 1)
       |    case rev: ReverseNode => ${k.lc}At(rev.base, rev.base.length - 1 - i)$rngCase
       |    case _ => ${k.dflt}
       |  }""".stripMargin
  }

  private def farrayOps: String = {
    val dfs = opKinds.map(dfsDef).mkString("\n")
    val ats = opKinds.map(atDef).mkString("\n")

    // Reference reads cast the leaf array to Array[A] (checkcast hoisted out of the loop at the
    // concrete inline call site; empty leaves never evaluate it). Primitive arrays can't cast to
    // Array[A] (erases to Object[]), so they read directly.
    def read(k: Kind): String = if k.name == "Ref" then "r.wrap(a.asInstanceOf[Array[A]](i))" else "r.wrap(a(i))"
    def readOne(k: Kind): String = if k.name == "Ref" then "r.wrap(v.asInstanceOf[A])" else "r.wrap(v)"
    def alloc(k: Kind, rv: String): String =
      if k.name == "Ref" then s"$rv.ct.newArray(n).asInstanceOf[Array[Object]]" else s"new Array[${k.arr}](n)"
    // a ref write stores r.Prim (= A, runtime <: Object) into an Object[] — cast it (no-op); prims store directly.
    def wr(k: Kind, e: String): String = if k.name == "Ref" then s"($e).asInstanceOf[Object]" else e
    def dispatchA(body: Kind => String): String =
      "summonFrom {\n" + opKinds.map(k => s"      case r: ${k.name}Repr[A] => ${body(k)}").mkString("\n") + "\n    }"
    def dispatchB(body: Kind => String): String =
      "summonFrom {\n" + opKinds.map(k => s"      case r: ${k.name}Repr[B] => ${body(k)}").mkString("\n") + "\n    }"

    val foldLeft = dispatchA(k =>
      s"dfs${k.name}(xs)((a, n) => { var i = 0; while (i < n) { acc = op(acc, ${read(k)}); i += 1 } })(v => { acc = op(acc, ${readOne(k)}) })")
    val foreach = dispatchA(k =>
      s"dfs${k.name}(xs)((a, n) => { var i = 0; while (i < n) { f(${read(k)}); i += 1 } })(v => { f(${readOne(k)}) })")
    val mapM = "summonFrom {\n" + opKinds.map { ka =>
      val inner = "summonFrom {\n" + opKinds.map { kb =>
        s"          case rb: ${kb.name}Repr[B] => { val out = ${alloc(kb, "rb")}; var o = 0; dfs${ka.name}(xs)((a, len) => { var i = 0; while (i < len) { out(o) = ${wr(kb, s"rb.unwrap(f(${read(ka)}))")}; o += 1; i += 1 } })(v => { out(o) = ${wr(kb, s"rb.unwrap(f(${readOne(ka)}))")}; o += 1 }); new ${kb.name}Arr(out, n) }"
      }.mkString("\n") + "\n        }"
      s"      case r: ${ka.name}Repr[A] => $inner"
    }.mkString("\n") + "\n    }"
    val filter = dispatchA(k =>
      s"{ val out = ${alloc(k, "r")}; var o = 0; dfs${k.name}(xs)((a, len) => { var i = 0; while (i < len) { val e = ${read(k)}; if (p(e)) { out(o) = ${wr(k, "r.unwrap(e)")}; o += 1 }; i += 1 } })(v => { val e = ${readOne(k)}; if (p(e)) { out(o) = ${wr(k, "r.unwrap(e)")}; o += 1 } }); if (o == n) xs else if (o == 0) ${k.name}Arr.EMPTY else new ${k.name}Arr(java.util.Arrays.copyOf(out, o), o) }")
    val contains = dispatchA(k =>
      if k.name == "Ref" then s"dfs${k.name}(xs)((a, n) => { var i = 0; while (i < n) { if (${read(k)} == elem) found = true; i += 1 } })(v => { if (${readOne(k)} == elem) found = true })"
      else s"{ val e = r.unwrap(elem); dfs${k.name}(xs)((a, n) => { var i = 0; while (i < n) { if (a(i) == e) found = true; i += 1 } })(v => { if (v == e) found = true }) }")
    val applyAt = dispatchA(k =>
      if k.name == "Ref" then s"r.wrap(${k.lc}At(xs, i).asInstanceOf[A])" else s"r.wrap(${k.lc}At(xs, i))")
    val flatMapEmpty = dispatchB(k => s"(${k.name}Arr.EMPTY: FBase)")
    val flatMapRead = dispatchA(k =>
      s"dfs${k.name}(xs)((a, n) => { var i = 0; while (i < n) { acc = acc.concat(f(${read(k)})); i += 1 } })(v => { acc = acc.concat(f(${readOne(k)})) })")
    val updated = dispatchA(k =>
      s"{ val out = ${alloc(k, "r")}; var o = 0; dfs${k.name}(xs)((a, len) => { System.arraycopy(a, 0, out, o, len); o += len })(v => { out(o) = v; o += 1 }); out(index) = ${wr(k, "r.unwrap(elem.asInstanceOf[A])")}; new ${k.name}Arr(out, n) }")
    val append = dispatchB(k => s"new ${k.name}Append(xs, r.unwrap(elem))")
    val prepend = dispatchA(k => s"new ${k.name}Prepend(r.unwrap(elem), xs)")
    val emptyB = dispatchA(k => s"${k.name}Arr.EMPTY")
    val tabulate = dispatchA(k =>
      s"if (n <= 0) ${k.name}Arr.EMPTY else { val out = ${alloc(k, "r")}; var i = 0; while (i < n) { out(i) = ${wr(k, "r.unwrap(f(i))")}; i += 1 }; new ${k.name}Arr(out, n) }")
    val applyVar = dispatchA(k =>
      s"if (as.isEmpty) ${k.name}Arr.EMPTY else { val n = as.length; val out = ${alloc(k, "r")}; var i = 0; while (i < n) { out(i) = ${wr(k, "r.unwrap(as(i))")}; i += 1 }; new ${k.name}Arr(out, n) }")
    val fromArr = dispatchA(k => s"new ${k.name}Arr(as.asInstanceOf[Array[${k.arr}]], as.length)")

    s"""package farray
       |
       |import scala.compiletime.summonFrom
       |
       |// GENERATED by GenCores — do not edit. Per-kind specialized combinator implementations.
       |object FArrayOps {
       |$dfs
       |$ats
       |
       |  inline def emptyImpl[A]: FBase = $emptyB
       |  inline def applyImpl[A](as: Seq[A]): FBase = $applyVar
       |  inline def tabulateImpl[A](n: Int)(inline f: Int => A): FBase = $tabulate
       |  inline def fromArrayImpl[A](as: Array[A]): FBase = $fromArr
       |  inline def foldLeftImpl[A, Z](xs: FBase, z: Z)(inline op: (Z, A) => Z): Z = {
       |    var acc = z
       |    $foldLeft
       |    acc
       |  }
       |  inline def foreachImpl[A](xs: FBase)(inline f: A => Unit): Unit = $foreach
       |  inline def mapImpl[A, B](xs: FBase)(inline f: A => B): FBase = {
       |    val n = xs.length
       |    $mapM
       |  }
       |  inline def filterImpl[A](xs: FBase)(inline p: A => Boolean): FBase = {
       |    val n = xs.length
       |    $filter
       |  }
       |  inline def containsImpl[A](xs: FBase, elem: A): Boolean = {
       |    var found = false
       |    $contains
       |    found
       |  }
       |  inline def applyAtImpl[A](xs: FBase, i: Int): A = $applyAt
       |  inline def flatMapImpl[A, B](xs: FBase)(inline f: A => FBase): FBase = {
       |    var acc: FBase = $flatMapEmpty
       |    $flatMapRead
       |    acc
       |  }
       |  inline def updatedImpl[A, B](xs: FBase, index: Int, elem: B): FBase = {
       |    val n = xs.length
       |    $updated
       |  }
       |  inline def appendImpl[A, B](xs: FBase, elem: B): FBase = $append
       |  inline def prependImpl[A](elem: A, xs: FBase): FBase = $prepend
       |}
       |""".stripMargin
  }

  private def fbase: String = {
    val leaves = prims.flatMap(p => List(s"${p.name}Arr", s"${p.name}Append", s"${p.name}Prepend"))
    val permits = (leaves ++ List("RefArr", "RefAppend", "RefPrepend", "Concat", "RangeNode", "ReverseNode")).mkString(", ")
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit.
       |public sealed abstract class FBase permits $permits {
       |    public final int length;
       |    protected FBase(int length) { this.length = length; }
       |
       |    public abstract Object applyBoxed(int i);
       |    public abstract FBase take(int n);
       |    public abstract FBase drop(int n);
       |    public abstract FBase slice(int from, int until);
       |    public abstract FBase reverse();
       |    public abstract FBase init();
       |
       |    /** O(1) concat: builds a Concat tree node; never casts, so heterogeneous kinds are safe. */
       |    public final FBase concat(FBase that) {
       |        if (that.length == 0) return this;
       |        if (this.length == 0) return that;
       |        return new Concat(this, that);
       |    }
       |}
       |""".stripMargin
  }

  private def primCore(p: Prim): String = {
    val cls = s"${p.name}Arr"
    s"""package farray;
       |
       |import java.util.Arrays;
       |
       |// GENERATED by GenCores — do not edit. ${p.jt}[]-backed specialized leaf.
       |public final class $cls extends FBase {
       |    public final ${p.jt}[] arr;
       |    public $cls(${p.jt}[] arr, int length) { super(length); this.arr = arr; }
       |    public static final $cls EMPTY = new $cls(new ${p.jt}[0], 0);
       |
       |    @Override public Object applyBoxed(int i) { return ${p.boxed}.valueOf(arr[i]); }
       |
       |    @Override public FBase take(int n) {
       |        int newLen = n < 0 ? 0 : (n > length ? length : n);
       |        if (newLen == 0) return EMPTY;
       |        if (newLen == length) return this;
       |        return new $cls(Arrays.copyOfRange(arr, 0, newLen), newLen);
       |    }
       |    @Override public FBase drop(int n) {
       |        int d = n < 0 ? 0 : (n > length ? length : n);
       |        int newLen = length - d;
       |        if (newLen == length) return this;
       |        if (newLen == 0) return EMPTY;
       |        return new $cls(Arrays.copyOfRange(arr, d, length), newLen);
       |    }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from;
       |        int hi = until > length ? length : until;
       |        if (lo >= hi) return EMPTY;
       |        if (lo == 0 && hi == length) return this;
       |        return new $cls(Arrays.copyOfRange(arr, lo, hi), hi - lo);
       |    }
       |    @Override public FBase reverse() { return length < 2 ? this : new ReverseNode(this); }
       |    @Override public FBase init() { return new $cls(arr, length - 1); }
       |
       |    @Override public int hashCode() {
       |        int result = 1;
       |        for (int i = 0; i < length; i++) result = 31 * result + ${p.boxed}.hashCode(arr[i]);
       |        return result;
       |    }
       |    @Override public boolean equals(Object obj) {
       |        if (this == obj) return true;
       |        if (!(obj instanceof $cls)) return Concat.elementwiseEquals(this, obj);
       |        $cls other = ($cls) obj;
       |        if (other.length != length) return false;
       |        for (int i = 0; i < length; i++) if (arr[i] != other.arr[i]) return false;
       |        return true;
       |    }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin
  }

  private def refArr: String =
    s"""package farray;
       |
       |import java.util.Arrays;
       |
       |// GENERATED by GenCores — do not edit. Object[]-backed leaf for reference element types.
       |public final class RefArr extends FBase {
       |    public final Object[] arr;
       |    public RefArr(Object[] arr, int length) { super(length); this.arr = arr; }
       |    public static final RefArr EMPTY = new RefArr(new Object[0], 0);
       |
       |    @Override public Object applyBoxed(int i) { return arr[i]; }
       |
       |    @Override public FBase take(int n) {
       |        int newLen = n < 0 ? 0 : (n > length ? length : n);
       |        if (newLen == 0) return EMPTY;
       |        if (newLen == length) return this;
       |        return new RefArr(Arrays.copyOfRange(arr, 0, newLen), newLen);
       |    }
       |    @Override public FBase drop(int n) {
       |        int d = n < 0 ? 0 : (n > length ? length : n);
       |        int newLen = length - d;
       |        if (newLen == length) return this;
       |        if (newLen == 0) return EMPTY;
       |        return new RefArr(Arrays.copyOfRange(arr, d, length), newLen);
       |    }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from;
       |        int hi = until > length ? length : until;
       |        if (lo >= hi) return EMPTY;
       |        if (lo == 0 && hi == length) return this;
       |        return new RefArr(Arrays.copyOfRange(arr, lo, hi), hi - lo);
       |    }
       |    @Override public FBase reverse() { return length < 2 ? this : new ReverseNode(this); }
       |    @Override public FBase init() { return new RefArr(arr, length - 1); }
       |
       |    @Override public int hashCode() {
       |        int result = 1;
       |        for (int i = 0; i < length; i++) { Object e = arr[i]; result = 31 * result + (e == null ? 0 : e.hashCode()); }
       |        return result;
       |    }
       |    @Override public boolean equals(Object obj) {
       |        if (this == obj) return true;
       |        if (!(obj instanceof RefArr)) return Concat.elementwiseEquals(this, obj);
       |        RefArr other = (RefArr) obj;
       |        if (other.length != length) return false;
       |        for (int i = 0; i < length; i++) {
       |            Object x = arr[i], y = other.arr[i];
       |            if (x == null ? y != null : !x.equals(y)) return false;
       |        }
       |        return true;
       |    }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin

  private def concat: String =
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Tree node: O(1) concat, structural ops recurse (Java
       |// recursion is fine here — only the inline Scala combinators must avoid recursion to keep the
       |// element op spliced). Element traversal uses an explicit stack in the Scala combinators.
       |public final class Concat extends FBase {
       |    public final FBase left;
       |    public final FBase right;
       |    public Concat(FBase left, FBase right) {
       |        super(left.length + right.length);
       |        this.left = left;
       |        this.right = right;
       |    }
       |
       |    @Override public Object applyBoxed(int i) {
       |        return i < left.length ? left.applyBoxed(i) : right.applyBoxed(i - left.length);
       |    }
       |    @Override public FBase take(int n) {
       |        if (n <= 0) return left.take(0);
       |        if (n >= length) return this;
       |        if (n <= left.length) return left.take(n);
       |        return new Concat(left, right.take(n - left.length));
       |    }
       |    @Override public FBase drop(int n) {
       |        if (n <= 0) return this;
       |        if (n >= length) return right.drop(right.length);
       |        if (n >= left.length) return right.drop(n - left.length);
       |        return new Concat(left.drop(n), right);
       |    }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from;
       |        int hi = until > length ? length : until;
       |        if (lo >= hi) return left.take(0);
       |        return drop(lo).take(hi - lo);
       |    }
       |    @Override public FBase reverse() { return new Concat(right.reverse(), left.reverse()); }
       |    @Override public FBase init() { return take(length - 1); }

       |
       |    @Override public int hashCode() {
       |        int result = 1;
       |        for (int i = 0; i < length; i++) { Object e = applyBoxed(i); result = 31 * result + (e == null ? 0 : e.hashCode()); }
       |        return result;
       |    }
       |    @Override public boolean equals(Object obj) { return elementwiseEquals(this, obj); }
       |    @Override public String toString() { return render(this); }
       |
       |    /** Shared element-wise equality across any two cores (used when concrete kinds differ). */
       |    static boolean elementwiseEquals(FBase self, Object obj) {
       |        if (self == obj) return true;
       |        if (!(obj instanceof FBase)) return false;
       |        FBase other = (FBase) obj;
       |        if (other.length != self.length) return false;
       |        for (int i = 0; i < self.length; i++) {
       |            Object x = self.applyBoxed(i), y = other.applyBoxed(i);
       |            if (x == null ? y != null : !x.equals(y)) return false;
       |        }
       |        return true;
       |    }
       |    static String render(FBase self) {
       |        StringBuilder sb = new StringBuilder("FArray(");
       |        for (int i = 0; i < self.length; i++) { if (i != 0) sb.append(", "); sb.append(self.applyBoxed(i)); }
       |        return sb.append(')').toString();
       |    }
       |}
       |""".stripMargin

  /** Closed-form Int range — O(1) construct, O(1) index/take/drop/reverse, never materializes. Int kind only. */
  private def rangeNode: String =
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Lazy closed-form Int range node.
       |public final class RangeNode extends FBase {
       |    public final int start;
       |    public final int step;
       |    public RangeNode(int start, int step, int length) { super(length); this.start = start; this.step = step; }
       |    @Override public Object applyBoxed(int i) { return Integer.valueOf(start + i * step); }
       |    @Override public FBase take(int n) {
       |        int m = n < 0 ? 0 : (n > length ? length : n);
       |        return m == length ? this : (m == 0 ? IntArr.EMPTY : new RangeNode(start, step, m));
       |    }
       |    @Override public FBase drop(int n) {
       |        int d = n < 0 ? 0 : (n > length ? length : n);
       |        return d == 0 ? this : (d == length ? IntArr.EMPTY : new RangeNode(start + d * step, step, length - d));
       |    }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from, hi = until > length ? length : until;
       |        if (lo >= hi) return IntArr.EMPTY;
       |        return new RangeNode(start + lo * step, step, hi - lo);
       |    }
       |    @Override public FBase reverse() { return length < 2 ? this : new RangeNode(start + (length - 1) * step, -step, length); }
       |    @Override public FBase init() { return take(length - 1); }
       |    @Override public int hashCode() { int r = 1; for (int i = 0; i < length; i++) r = 31 * r + Integer.hashCode(start + i * step); return r; }
       |    @Override public boolean equals(Object o) { return Concat.elementwiseEquals(this, o); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin

  /** Lazy reverse — O(1) construct, shares the base; index/dfs read the base at the mirrored position. */
  private def reverseNode: String =
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Lazy reverse node (kind-agnostic; base shared).
       |public final class ReverseNode extends FBase {
       |    public final FBase base;
       |    public ReverseNode(FBase base) { super(base.length); this.base = base; }
       |    @Override public Object applyBoxed(int i) { return base.applyBoxed(length - 1 - i); }
       |    @Override public FBase take(int n) {
       |        int m = n < 0 ? 0 : (n > length ? length : n);
       |        if (m == 0) return base.take(0);
       |        return new ReverseNode(base.drop(length - m));
       |    }
       |    @Override public FBase drop(int n) {
       |        int d = n < 0 ? 0 : (n > length ? length : n);
       |        if (d == length) return base.take(0);
       |        return new ReverseNode(base.take(length - d));
       |    }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from, hi = until > length ? length : until;
       |        if (lo >= hi) return base.take(0);
       |        return drop(lo).take(hi - lo);
       |    }
       |    @Override public FBase reverse() { return base; }
       |    @Override public FBase init() { return take(length - 1); }
       |    @Override public int hashCode() { int r = 1; for (int i = 0; i < length; i++) { Object e = applyBoxed(i); r = 31 * r + (e == null ? 0 : e.hashCode()); } return r; }
       |    @Override public boolean equals(Object o) { return Concat.elementwiseEquals(this, o); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin

  private def primAppend(p: Prim): String = {
    val cls = s"${p.name}Append"
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Unary append node (base + one ${p.jt}, base shared).
       |public final class $cls extends FBase {
       |    public final FBase base;
       |    public final ${p.jt} elem;
       |    public $cls(FBase base, ${p.jt} elem) { super(base.length + 1); this.base = base; this.elem = elem; }
       |    @Override public Object applyBoxed(int i) { return i < base.length ? base.applyBoxed(i) : ${p.boxed}.valueOf(elem); }
       |    @Override public FBase take(int n) { return n >= length ? this : base.take(n); }
       |    @Override public FBase drop(int n) {
       |        if (n <= 0) return this;
       |        if (n >= length) return base.take(0);
       |        return new $cls(base.drop(n), elem);
       |    }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from; int hi = until > length ? length : until;
       |        if (lo >= hi) return base.take(0);
       |        return drop(lo).take(hi - lo);
       |    }
       |    @Override public FBase reverse() { return new ${p.name}Prepend(elem, base.reverse()); }
       |    @Override public FBase init() { return base; }
       |    @Override public int hashCode() {
       |        int result = 1;
       |        for (int i = 0; i < length; i++) { Object e = applyBoxed(i); result = 31 * result + (e == null ? 0 : e.hashCode()); }
       |        return result;
       |    }
       |    @Override public boolean equals(Object obj) { return Concat.elementwiseEquals(this, obj); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin
  }

  private def primPrepend(p: Prim): String = {
    val cls = s"${p.name}Prepend"
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Unary prepend node (one ${p.jt} + base, base shared).
       |public final class $cls extends FBase {
       |    public final ${p.jt} elem;
       |    public final FBase base;
       |    public $cls(${p.jt} elem, FBase base) { super(base.length + 1); this.elem = elem; this.base = base; }
       |    @Override public Object applyBoxed(int i) { return i == 0 ? ${p.boxed}.valueOf(elem) : base.applyBoxed(i - 1); }
       |    @Override public FBase take(int n) {
       |        if (n <= 0) return base.take(0);
       |        if (n >= length) return this;
       |        return new $cls(elem, base.take(n - 1));
       |    }
       |    @Override public FBase drop(int n) {
       |        if (n <= 0) return this;
       |        if (n >= length) return base.take(0);
       |        return base.drop(n - 1);
       |    }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from; int hi = until > length ? length : until;
       |        if (lo >= hi) return base.take(0);
       |        return drop(lo).take(hi - lo);
       |    }
       |    @Override public FBase reverse() { return new ${p.name}Append(base.reverse(), elem); }
       |    @Override public FBase init() { return take(length - 1); }
       |    @Override public int hashCode() {
       |        int result = 1;
       |        for (int i = 0; i < length; i++) { Object e = applyBoxed(i); result = 31 * result + (e == null ? 0 : e.hashCode()); }
       |        return result;
       |    }
       |    @Override public boolean equals(Object obj) { return Concat.elementwiseEquals(this, obj); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin
  }

  private def refUnary(kind: String): String = {
    val cls = s"Ref$kind"
    val isAppend = kind == "Append"
    val fields = if isAppend then "public final FBase base;\n    public final Object elem;"
                 else "public final Object elem;\n    public final FBase base;"
    val ctorArgs = if isAppend then "FBase base, Object elem" else "Object elem, FBase base"
    val ctorBody = if isAppend then "this.base = base; this.elem = elem;" else "this.elem = elem; this.base = base;"
    val applyB = if isAppend then "i < base.length ? base.applyBoxed(i) : elem" else "i == 0 ? elem : base.applyBoxed(i - 1)"
    val take = if isAppend then "return n >= length ? this : base.take(n);"
               else "if (n <= 0) return base.take(0); if (n >= length) return this; return new RefPrepend(elem, base.take(n - 1));"
    val drop = if isAppend then "if (n <= 0) return this; if (n >= length) return base.take(0); return new RefAppend(base.drop(n), elem);"
               else "if (n <= 0) return this; if (n >= length) return base.take(0); return base.drop(n - 1);"
    val reverse = if isAppend then "return new RefPrepend(elem, base.reverse());" else "return new RefAppend(base.reverse(), elem);"
    val init = if isAppend then "return base;" else "return take(length - 1);"
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Unary $kind node for reference elements (base shared).
       |public final class $cls extends FBase {
       |    $fields
       |    public $cls($ctorArgs) { super(base.length + 1); $ctorBody }
       |    @Override public Object applyBoxed(int i) { return $applyB; }
       |    @Override public FBase take(int n) { $take }
       |    @Override public FBase drop(int n) { $drop }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from; int hi = until > length ? length : until;
       |        if (lo >= hi) return base.take(0);
       |        return drop(lo).take(hi - lo);
       |    }
       |    @Override public FBase reverse() { $reverse }
       |    @Override public FBase init() { $init }
       |    @Override public int hashCode() {
       |        int result = 1;
       |        for (int i = 0; i < length; i++) { Object e = applyBoxed(i); result = 31 * result + (e == null ? 0 : e.hashCode()); }
       |        return result;
       |    }
       |    @Override public boolean equals(Object obj) { return Concat.elementwiseEquals(this, obj); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin
  }
}
