package farray

import bleep.*
import bleep.internal.FileUtils

import java.nio.file.Files

/** Generates the sealed FArray core hierarchy: `FBase` (abstract storage-shuffling API + a concrete O(1) `concat` that builds a `Concat` tree node) + one
  * `<Name>Arr` leaf per primitive + the `Object[]`-backed `RefArr` leaf + the `Concat` tree node. Wired as `farray`'s sourcegen.
  *
  * Element-touching combinators and element-insert ops (`:+`/`+:`/`updated`) live in Scala (inline, specialized) — NOT here. Adding a primitive = one row in
  * `prims`.
  */
object GenCores extends BleepCodegenScript("GenCores") {

  final case class Prim(name: String, jt: String, boxed: String)

  val prims: List[Prim] = List(
    Prim("Int", "int", "Integer"),
    Prim("Long", "long", "Long"),
    Prim("Double", "double", "Double"),
    Prim("Float", "float", "Float"),
    Prim("Short", "short", "Short"),
    Prim("Byte", "byte", "Byte"),
    Prim("Char", "char", "Character"),
    Prim("Boolean", "boolean", "Boolean")
  )

  override def run(started: Started, commands: Commands, targets: List[GenCores.Target], args: List[String]): Unit =
    targets.foreach { target =>
      val dir = target.sources.resolve("farray")
      FileUtils.deleteDirectory(target.sources)
      Files.createDirectories(dir)
      Files.writeString(dir.resolve("FBase.java"), fbase)
      Files.writeString(dir.resolve("RefArr.java"), refArr)
      Files.writeString(dir.resolve("RefAppend.java"), refUnary("Append"))
      Files.writeString(dir.resolve("RefPrepend.java"), refUnary("Prepend"))
      Files.writeString(dir.resolve("Concat.java"), concat)
      Files.writeString(dir.resolve("RangeNode.java"), rangeNode)
      Files.writeString(dir.resolve("ReverseNode.java"), reverseNode)
      Files.writeString(dir.resolve("SliceNode.java"), sliceNode)
      Files.writeString(dir.resolve("Hashing.java"), hashing)
      Files.writeString(dir.resolve("Empty.java"), emptyNode)
      padKinds.foreach { case (name, jt, boxed) => Files.writeString(dir.resolve(s"${name}Pad.java"), padNode(name, jt, boxed)) }
      padKinds.foreach { case (name, jt, boxed) => Files.writeString(dir.resolve(s"${name}Updated.java"), updatedNode(name, jt, boxed)) }
      padKinds.foreach { case (name, jt, boxed) => Files.writeString(dir.resolve(s"${name}One.java"), oneNode(name, jt, boxed)) }
      prims.foreach { p =>
        Files.writeString(dir.resolve(s"${p.name}Arr.java"), primCore(p))
        Files.writeString(dir.resolve(s"${p.name}Append.java"), primAppend(p))
        Files.writeString(dir.resolve(s"${p.name}Prepend.java"), primPrepend(p))
      }
      Files.writeString(dir.resolve("Repr.scala"), reprSrc)
      Files.writeString(dir.resolve("FArrayOps.scala"), farrayOps)
    }

  /** Unified array-representation evidence — subsumes primitive specialization, value-class/opaque unwrapping (Prim + inline wrap/unwrap), and reference
    * ClassTag (RefRepr.ct). One per concrete A; absent for abstract A ⇒ summonFrom fails ⇒ compile error (specialize-or-fail).
    */
  private def reprSrc: String = {
    val subtraits = opKinds
      .map { k =>
        if k.name == "Ref" then "trait RefRepr[A] extends Repr[A] { type Prim = A }"
        else s"trait ${k.name}Repr[A] extends Repr[A] { type Prim = ${k.arr} }"
      }
      .mkString("\n")
    val givens = opKinds
      .map { k =>
        if k.name == "Ref" then "  given refRepr[A <: AnyRef]: RefRepr[A] with { inline def unwrap(a: A): A = a; inline def wrap(p: A): A = p }"
        else s"  given ${k.lc}Repr: ${k.name}Repr[${k.arr}] with { inline def unwrap(a: ${k.arr}): ${k.arr} = a; inline def wrap(p: ${k.arr}): ${k.arr} = p }"
      }
      .mkString("\n")
    s"""package farray
       |
       |// GENERATED by GenCores — do not edit.
       |sealed trait Repr[A] {
       |  type Prim
       |  inline def unwrap(a: A): Prim
       |  inline def wrap(p: Prim): A
       |}
       |$subtraits
       |
       |object Repr {
       |$givens
       |}
       |""".stripMargin
  }

  // ===== generated per-kind Scala combinators (the read×write matrix lives here, not hand-written) =====

  /** name=core prefix (Int/Long/Double/Ref); arr=Scala array elem type; pat=erasedValue pattern; dflt=zero. */
  /** the primitive boxing facet of a Kind (absent ⇒ a reference): the boxed wrapper type plus how to box (`to`) and unbox (`from`) the underlying `prim` value.
    */
  final case class Box(wrapper: String, prim: String) {
    def to(v: String): String = s"$wrapper.valueOf($v)" // box:   prim -> Object
    def from(v: String): String = s"scala.runtime.BoxesRunTime.unboxTo$prim($v)" // unbox: Object -> prim
  }

  /** specCh: the JVM erasure descriptor char — I/J/D for primitives, L (object) for references — which is also the char in stdlib @specialized class names
    * (Tuple2$mcII$sp etc.). prim: present iff a primitive.
    */
  final case class Kind(name: String, arr: String, pat: String, dflt: String, specCh: String, prim: Option[Box]) {
    def lc = name.toLowerCase
    def isPrim: Boolean = prim.isDefined

    /** box a `$arr`-typed value to an Object (pass-through for a reference). */
    def box(v: String): String = prim match { case Some(b) => b.to(v); case None => v }

    /** unbox an Object expression to the element type (auto-unboxes for prims; cast for references). */
    def unbox(v: String): String = prim match { case Some(b) => b.from(v); case None => s"($v).asInstanceOf[$arr]" }
  }

  // Start with the common numeric kinds + reference; add rows here to cover more primitives.
  val opKinds: List[Kind] = List(
    Kind("Int", "Int", "Int", "0", "I", Some(Box("java.lang.Integer", "Int"))),
    Kind("Long", "Long", "Long", "0L", "J", Some(Box("java.lang.Long", "Long"))),
    Kind("Double", "Double", "Double", "0.0", "D", Some(Box("java.lang.Double", "Double"))),
    Kind("Ref", "Object", "AnyRef", "null", "L", None)
  )

  private val grow =
    "if (sp + 2 > stack.length) { val ns = stack.length * 2; stack = java.util.Arrays.copyOf(stack, ns); tail = java.util.Arrays.copyOf(tail, ns); isTail = java.util.Arrays.copyOf(isTail, ns) }"

  // The traversal body, parameterized by how a leaf-run (onL) and a single element (onO) are consumed, so we
  // can emit it as both the inline `dfs${k}` (callbacks inlined) and the non-inline `dfsC${k}` (consumer
  // method calls — compiled once, so combinators don't dump the whole walk at every use-site).
  private def dfsBody(k: Kind, onL: String, onO: String): String = {
    val rngCase = if k.name == "Int" then
      s"\n       |        case rng: RangeNode => { val rn = rng.length; var ri = 0; while (ri < rn) { $onO(rng.start + ri * rng.step); ri += 1 } }"
    else ""
    val padRead = if k.name == "Ref" then "pad.base.applyBoxed(pi)" else s"${k.lc}At(pad.base, pi)"
    // `cur`-driven walk: Prepend is a tail (continue with base), Reverse/Pad/Slice/Range/Updated emit in a
    // loop — none push. Only Concat/Append defer a sibling, so the stack stays null until one actually does.
    val ensure =
      s"if (stack == null) { stack = new Array[FBase](16); tail = new Array[${k.arr}](16); isTail = new Array[Boolean](16) } else if (sp == stack.length) { val nl = sp * 2; stack = java.util.Arrays.copyOf(stack, nl); tail = java.util.Arrays.copyOf(tail, nl); isTail = java.util.Arrays.copyOf(isTail, nl) }"
    s"""    var cur: FBase = root
       |    var stack: Array[FBase] = null; var tail: Array[${k.arr}] = null; var isTail: Array[Boolean] = null; var sp = 0
       |    while (cur != null) {
       |      var cont: FBase = null
       |      cur match {
       |        case leaf: ${k.name}Arr => $onL(leaf.arr, leaf.length)
       |        case o: ${k.name}One => $onO(o.elem)
       |        case p: ${k.name}Prepend => { $onO(p.elem); cont = p.base }
       |        case a: ${k.name}Append => { $ensure; tail(sp) = a.elem; isTail(sp) = true; sp += 1; cont = a.base }
       |        case c: Concat => { $ensure; stack(sp) = c.right; isTail(sp) = false; sp += 1; cont = c.left }
       |        case rev: ReverseNode => { val rn = rev.length; rev.base match { case lf: ${k.name}Arr => { val la = lf.arr; var ri = 0; while (ri < rn) { $onO(la(rn - 1 - ri)); ri += 1 } }; case _ => { var ri = 0; while (ri < rn) { $onO(${k.lc}At(rev.base, rn - 1 - ri)); ri += 1 } } } }
       |        case pad: ${k.name}Pad => { val bl = pad.base.length; pad.base match { case lf: ${k.name}Arr => { val la = lf.arr; var pi = 0; while (pi < bl) { $onO(la(pi)); pi += 1 } }; case _ => { var pi = 0; while (pi < bl) { $onO($padRead); pi += 1 } } }; val pf = pad.filler; var pj = bl; val pn = pad.length; while (pj < pn) { $onO(pf); pj += 1 } }
       |        case u: ${k.name}Updated => { val un = u.length; u.base match { case lf: ${k.name}Arr => { val la = lf.arr; var ui = 0; while (ui < un) { $onO(if (ui == u.index) u.elem else la(ui)); ui += 1 } }; case _ => { val mout = materialize${k.name}(u); $onL(mout, mout.length) } } }
       |        case s: SliceNode => { val sn = s.length; val so = s.offset; s.base match { case lf: ${k.name}Arr => { val la = lf.arr; var si = 0; while (si < sn) { $onO(la(so + si)); si += 1 } }; case _ => { var si = 0; while (si < sn) { $onO(${k.lc}At(s.base, so + si)); si += 1 } } } }$rngCase
       |        case _ => ()
       |      }
       |      if (cont != null) cur = cont
       |      else { cur = null; while (sp > 0 && cur == null) { sp -= 1; if (isTail(sp)) $onO(tail(sp)) else cur = stack(sp) } }
       |    }""".stripMargin
  }
  // consumer (2-method) form: non-inline, one compiled impl per kind. onLeaf fires per leaf-run, onOne per
  // single element — both cheap (O(#runs)); the per-element op stays inlined inside the consumer at the site.
  private def dfsConsumer(k: Kind): String =
    s"abstract class ${k.name}Dfs { def onLeaf(a: Array[${k.arr}], len: Int): Unit; def onOne(v: ${k.arr}): Unit }"
  private def dfsCDef(k: Kind): String =
    s"""  def dfsC${k.name}(root: FBase, c: ${k.name}Dfs): Unit = {
       |${dfsBody(k, "c.onLeaf", "c.onOne")}
       |  }""".stripMargin

  // The iterator is a trivial flat-array cursor (2 fields → escape analysis scalar-replaces it when consumed
  // inline → foreach speed). A leaf hands its backing array straight in (no copy, lazy); a tree is flattened
  // ONCE via the dfs we already have (materialize). So the tree-walk lives only in dfsBody — no second walker.
  private def cursorClass(k: Kind): String = {
    val nextBoxed = if k.name == "Ref" then s"next${k.name}()" else k.box(s"next${k.name}()")
    s"""final class ${k.name}Cursor(a: Array[${k.arr}], len: Int) extends scala.collection.AbstractIterator[Any] {
       |  private var pos = 0
       |  def hasNext: Boolean = pos < len
       |  override def knownSize: Int = len - pos
       |  def next${k.name}(): ${k.arr} = { val r = a(pos); pos += 1; r }
       |  def next(): Any = $nextBoxed
       |}""".stripMargin
  }

  private def atDef(k: Kind): String = {
    val rngCase = if k.name == "Int" then "\n       |    case rng: RangeNode => rng.start + i * rng.step" else ""
    val padBase = if k.name == "Ref" then "pad.base.applyBoxed(i)" else s"${k.lc}At(pad.base, i)"
    s"""  def ${k.lc}At(node: FBase, i: Int): ${k.arr} = node match {
       |    case leaf: ${k.name}Arr => leaf.arr(i)
       |    case o: ${k.name}One => o.elem
       |    case c: Concat => if (i < c.left.length) ${k.lc}At(c.left, i) else ${k.lc}At(c.right, i - c.left.length)
       |    case a: ${k.name}Append => if (i < a.base.length) ${k.lc}At(a.base, i) else a.elem
       |    case p: ${k.name}Prepend => if (i == 0) p.elem else ${k.lc}At(p.base, i - 1)
       |    case rev: ReverseNode => ${k.lc}At(rev.base, rev.base.length - 1 - i)
       |    case pad: ${k.name}Pad => if (i < pad.base.length) $padBase else pad.filler
       |    case u: ${k.name}Updated => if (i == u.index) u.elem else ${if k.name == "Ref" then "u.base.applyBoxed(i)" else s"${k.lc}At(u.base, i)"}
       |    case s: SliceNode => ${k.lc}At(s.base, s.offset + i)$rngCase
       |    case _ => ${k.dflt}
       |  }""".stripMargin
  }

  private def farrayOps: String = {
    val dfsConsumers = opKinds.map(dfsConsumer).mkString("\n")
    val cursors = opKinds.map(cursorClass).mkString("\n")
    val dfsC = opKinds.map(dfsCDef).mkString("\n")
    val ats = opKinds.map(atDef).mkString("\n")
    // Flatten a (possibly deep) Updated chain to a fresh leaf array, ONCE, so dfs can emit it tight via
    // onLeaf instead of walking the chain per element. Recursion applies overrides bottom-up => outer wins.
    val mat = opKinds
      .map(k =>
        s"""  def materialize${k.name}(node: FBase): Array[${k.arr}] = node match {
         |    case u: ${k.name}Updated => { val out = materialize${k.name}(u.base); out(u.index) = u.elem; out }
         |    case _ => { val out = new Array[${k.arr}](node.length); var o = 0; dfsC${k.name}(node, new ${k.name}Dfs { def onLeaf(a: Array[${k.arr}], len: Int): Unit = { System.arraycopy(a, 0, out, o, len); o += len }; def onOne(v: ${k.arr}): Unit = { out(o) = v; o += 1 } }); out }
         |  }""".stripMargin
      )
      .mkString("\n")
    // Stable bottom-up mergesort directly on a kind array, ping-ponging between two buffers (no per-level
    // copy-back). `less(x, y)` = x sorts strictly before y. Returns the sorted buffer (may be the input or temp).
    // non-inline per-kind flatMap result builder: dfs+System.arraycopy each inner into one flat array (dfs
    // inlined ONCE here, not at every flatMap call site). Ref takes the ClassTag so the array is typed.
    // non-inline flatMap helpers (compiled once, not re-inlined at every call site): grow the output array,
    // and copy ONE non-leaf inner into out (dfs).
    val flatMapCopyOne = opKinds
      .map(k =>
        s"""  def ensureCap${k.name}(out: Array[${k.arr}], needed: Int): Array[${k.arr}] =
         |    if (needed <= out.length) out else { var nc = out.length * 2; if (nc < needed) nc = needed; java.util.Arrays.copyOf(out, nc) }
         |  def flatMapCopyOne${k.name}(node: FBase, out: Array[${k.arr}], off0: Int): Unit = {
         |    var o = off0; dfsC${k.name}(node, new ${k.name}Dfs { def onLeaf(a: Array[${k.arr}], ln: Int): Unit = { System.arraycopy(a, 0, out, o, ln); o += ln }; def onOne(v: ${k.arr}): Unit = { out(o) = v; o += 1 } })
         |  }""".stripMargin
      )
      .mkString("\n")
    // Natural (run-adaptive) bottom-up mergesort. NON-inline (compiled once, not dumped at every sort site,
    // so multiple sorts in one method can't blow past the JIT method-size limit) with an unboxed primitive
    // comparator (${k.name}Less SAM — no boxing). Detects ascending runs and reverses strictly-descending
    // ones in place (already/reverse-sorted -> O(n)), then merges runs pairwise. Stable (merge prefers left;
    // ascending detection non-strict, descending strict). Ref sorts use java.util.Arrays.sort instead.
    val sortKinds = opKinds.filter(_.name != "Ref")
    val lessTraits = sortKinds.map(k => s"trait ${k.name}Less { def lt(a: ${k.arr}, b: ${k.arr}): Boolean }").mkString("\n")
    val sortArr = sortKinds
      .map(k =>
        s"""  def sort${k.name}(a: Array[${k.arr}], n: Int, less: ${k.name}Less): Array[${k.arr}] = {
         |    if (n < 2) a else {
         |      var sruns = new Array[Int](n + 1); var nr = 0; var i = 0
         |      while (i < n) {
         |        sruns(nr) = i; nr += 1; var j = i + 1
         |        if (j < n) {
         |          if (less.lt(a(j), a(i))) { j += 1; while (j < n && less.lt(a(j), a(j - 1))) j += 1; var lo = i; var hi = j - 1; while (lo < hi) { val t = a(lo); a(lo) = a(hi); a(hi) = t; lo += 1; hi -= 1 } }
         |          else { j += 1; while (j < n && !less.lt(a(j), a(j - 1))) j += 1 }
         |        }
         |        i = j
         |      }
         |      sruns(nr) = n
         |      var src = a; var dst = new Array[${k.arr}](n); var druns = new Array[Int](nr + 1)
         |      while (nr > 1) {
         |        var r = 0; var w = 0
         |        while (r < nr) {
         |          druns(w) = sruns(r); w += 1
         |          if (r + 1 < nr) {
         |            val lo = sruns(r); val mid = sruns(r + 1); val hi = sruns(r + 2)
         |            var x = lo; var y = mid; var k = lo
         |            while (x < mid && y < hi) { if (less.lt(src(y), src(x))) { dst(k) = src(y); y += 1 } else { dst(k) = src(x); x += 1 }; k += 1 }
         |            while (x < mid) { dst(k) = src(x); x += 1; k += 1 }
         |            while (y < hi) { dst(k) = src(y); y += 1; k += 1 }
         |            r += 2
         |          } else { val lo = sruns(r); System.arraycopy(src, lo, dst, lo, n - lo); r += 1 }
         |        }
         |        druns(w) = n
         |        val ts = src; src = dst; dst = ts; val tr = sruns; sruns = druns; druns = tr; nr = w
         |      }
         |      src
         |    }
         |  }""".stripMargin
      )
      .mkString("\n")

    // Reference reads cast the leaf array to Array[A] (checkcast hoisted out of the loop at the
    // concrete inline call site; empty leaves never evaluate it). Primitive arrays can't cast to
    // Array[A] (erases to Object[]), so they read directly.
    // Ref reads cast the ELEMENT (Object -> A), valid for any backing array — an Array[A] (i.e. Array[String])
    // cast would CCE on an Object[] backing (which materialize/sort produce, having no ClassTag).
    def read(k: Kind): String = if k.name == "Ref" then "r.wrap(a(i).asInstanceOf[A])" else "r.wrap(a(i))"
    def readOne(k: Kind): String = if k.name == "Ref" then "r.wrap(v.asInstanceOf[A])" else "r.wrap(v)"
    def alloc(k: Kind, rv: String): String =
      if k.name == "Ref" then s"new Array[Object](n)" else s"new Array[${k.arr}](n)"
    // a ref write stores r.Prim (= A, runtime <: Object) into an Object[] — cast it (no-op); prims store directly.
    def wr(k: Kind, e: String): String = if k.name == "Ref" then s"($e).asInstanceOf[Object]" else e
    // wrap a raw kind-array element back to A (for an inline user comparator); plain kind-array alloc
    def readVal(k: Kind, e: String): String = if k.name == "Ref" then s"r.wrap($e.asInstanceOf[A])" else s"r.wrap($e)"
    def allocPlain(k: Kind): String = s"new Array[${k.arr}](n)"
    def dispatchA(body: Kind => String): String =
      "summonFrom {\n" + opKinds.map(k => s"      case r: ${k.name}Repr[A] => ${body(k)}").mkString("\n") + "\n    }"
    def dispatchB(body: Kind => String): String =
      "summonFrom {\n" + opKinds.map(k => s"      case r: ${k.name}Repr[B] => ${body(k)}").mkString("\n") + "\n    }"

    val foldLeft = dispatchA(k =>
      s"{ var acc = z; val c = new ${k.name}Dfs { def onLeaf(a: Array[${k.arr}], len: Int): Unit = { var i = 0; while (i < len) { acc = op(acc, ${read(k)}); i += 1 } }; def onOne(v: ${k.arr}): Unit = { acc = op(acc, ${readOne(k)}) } }; dfsC${k.name}(xs, c); acc }"
    )
    val foreach = dispatchA(k =>
      s"{ val c = new ${k.name}Dfs { def onLeaf(a: Array[${k.arr}], len: Int): Unit = { var i = 0; while (i < len) { f(${read(k)}); i += 1 } }; def onOne(v: ${k.arr}): Unit = { f(${readOne(k)}) } }; dfsC${k.name}(xs, c) }"
    )
    // Fused short-circuiting scan: predicate-and-break in ONE branch per element (like Array's `if (p) return`),
    // no Step round-trip. `a` = element, break via `i = ln`. Leaf fast-path (tight) + <kind>At fallback.
    def scan(k: Kind, init: String, step: String, result: String): String =
      s"xs match { case leaf: ${k.name}Arr => { val ar = leaf.arr; val ln = leaf.length; var i = 0; $init; while (i < ln) { val a = ${readVal(k, "ar(i)")}; $step }; $result }; case _ => { val ln = xs.length; var i = 0; $init; while (i < ln) { val a = ${readVal(k, s"${k.lc}At(xs, i)")}; $step }; $result } }"
    val existsV = dispatchA(k => scan(k, "var res = false", "if (p(a)) { res = true; i = ln } else i += 1", "res"))
    val forallV = dispatchA(k => scan(k, "var res = true", "if (p(a)) i += 1 else { res = false; i = ln }", "res"))
    val findV = dispatchA(k => scan(k, "var res: Option[A] = None", "if (p(a)) { res = Some(a); i = ln } else i += 1", "res"))
    val indexWhereV = dispatchA(k => scan(k, "var res = -1", "if (p(a)) { res = i; i = ln } else i += 1", "res"))
    val indexOfV = dispatchA(k => scan(k, "var res = -1", "if (a == elem) { res = i; i = ln } else i += 1", "res"))
    val collectFirstV = dispatchA(k => scan(k, "var res: Option[B] = None", "if (pf.isDefinedAt(a)) { res = Some(pf(a)); i = ln } else i += 1", "res"))
    val prefixLenV = dispatchA(k => scan(k, "var res = ln", "if (p(a)) i += 1 else { res = i; i = ln }", "res"))
    val countV = dispatchA(k => scan(k, "var n = 0", "if (p(a)) n += 1; i += 1", "n")) // no break, tight leaf scan
    val iteratorV = dispatchA(k =>
      s"xs match { case leaf: ${k.name}Arr => new ${k.name}Cursor(leaf.arr, leaf.length); case _ => new ${k.name}Cursor(materialize${k.name}(xs), xs.length) }"
    )
    val foreachWhileV = dispatchA(k => scan(k, "()", "if (f(a)) i += 1 else i = ln", "()")) // breakable push: f returns false to stop
    // foldRight: leaf reads its backing array backward (no ReverseNode allocation); non-leaf walks <kind>At.
    val foldRightV = dispatchA(k =>
      s"xs match { case leaf: ${k.name}Arr => { val ar = leaf.arr; var acc = z; var i = leaf.length - 1; while (i >= 0) { acc = op(${readVal(k, "ar(i)")}, acc); i -= 1 }; acc }; case _ => { var acc = z; var i = xs.length - 1; while (i >= 0) { acc = op(${readVal(k, s"${k.lc}At(xs, i)")}, acc); i -= 1 }; acc } }"
    )
    val mapM = "summonFrom {\n" + opKinds
      .map { ka =>
        val inner = "summonFrom {\n" + opKinds
          .map { kb =>
            s"          case rb: ${kb.name}Repr[B] => { val out = ${alloc(kb, "rb")}; var o = 0; val c = new ${ka.name}Dfs { def onLeaf(a: Array[${ka.arr}], len: Int): Unit = { var i = 0; while (i < len) { out(o) = ${wr(kb, s"rb.unwrap(f(${read(ka)}))")}; o += 1; i += 1 } }; def onOne(v: ${ka.arr}): Unit = { out(o) = ${wr(kb, s"rb.unwrap(f(${readOne(ka)}))")}; o += 1 } }; dfsC${ka.name}(xs, c); new ${kb.name}Arr(out, n) }"
          }
          .mkString("\n") + "\n        }"
        s"      case r: ${ka.name}Repr[A] => $inner"
      }
      .mkString("\n") + "\n    }"
    val filter = dispatchA(k =>
      s"{ val out = ${alloc(k, "r")}; var o = 0; val c = new ${k.name}Dfs { def onLeaf(a: Array[${k.arr}], len: Int): Unit = { var i = 0; while (i < len) { val e = ${read(k)}; if (p(e)) { out(o) = ${wr(k, "r.unwrap(e)")}; o += 1 }; i += 1 } }; def onOne(v: ${k.arr}): Unit = { val e = ${readOne(k)}; if (p(e)) { out(o) = ${wr(k, "r.unwrap(e)")}; o += 1 } } }; dfsC${k.name}(xs, c); if (o == n) xs else if (o == 0) Empty.INSTANCE else new ${k.name}Arr(java.util.Arrays.copyOf(out, o), o) }"
    )
    // fused short-circuiting contains (prim compares unboxed against the unwrapped elem)
    val contains = dispatchA(k =>
      if k.name == "Ref" then
        s"xs match { case leaf: RefArr => { val ar = leaf.arr; val ln = leaf.length; var i = 0; var res = false; while (i < ln) { if (ar(i) == elem) { res = true; i = ln } else i += 1 }; res }; case _ => { val ln = xs.length; var i = 0; var res = false; while (i < ln) { if (refAt(xs, i) == elem) { res = true; i = ln } else i += 1 }; res } }"
      else
        s"{ val e = r.unwrap(elem); xs match { case leaf: ${k.name}Arr => { val ar = leaf.arr; val ln = leaf.length; var i = 0; var res = false; while (i < ln) { if (ar(i) == e) { res = true; i = ln } else i += 1 }; res }; case _ => { val ln = xs.length; var i = 0; var res = false; while (i < ln) { if (${k.lc}At(xs, i) == e) { res = true; i = ln } else i += 1 }; res } } }"
    )
    val applyAt = dispatchA(k => if k.name == "Ref" then s"r.wrap(${k.lc}At(xs, i).asInstanceOf[A])" else s"r.wrap(${k.lc}At(xs, i))")
    // mapConserve: scan for the first element f actually changes (reference !eq); if none, return xs with NO
    // allocation. Only on a change do we copy + apply f from there. (Prims always "change" — boxed eq — so
    // they materialize like map, which is correct: a primitive can't be conserved.)
    val mapConserve = dispatchA { k =>
      val applyFrom = s"var j = diff; while (j < n) { out(j) = ${wr(k, s"r.unwrap(f(${readVal(k, "out(j)")}))")}; j += 1 }; new ${k.name}Arr(out, n)"
      s"xs match { case leaf: ${k.name}Arr => { val sa = leaf.arr; val n = leaf.length; var i = 0; var diff = -1; while (i < n && diff < 0) { val a = ${readVal(k, "sa(i)")}; if (!(f(a).asInstanceOf[AnyRef] eq a.asInstanceOf[AnyRef])) diff = i; i += 1 }; if (diff < 0) xs else { val out = java.util.Arrays.copyOf(sa, n); $applyFrom } }; case _ => { val n = xs.length; var i = 0; var diff = -1; while (i < n && diff < 0) { val a = ${readVal(k, s"${k.lc}At(xs, i)")}; if (!(f(a).asInstanceOf[AnyRef] eq a.asInstanceOf[AnyRef])) diff = i; i += 1 }; if (diff < 0) xs else { val out = materialize${k.name}(xs); $applyFrom } } }"
    }
    // ONE pass, no inner buffer: dfs the source, and for each element append f(x)'s elements straight into a
    // growing output array (inline grow). The inner FArray is created, matched, and arraycopied within the
    // loop body, never stored -> escape analysis drops its wrapper, so each inner costs only its int[] (like
    // Array). dispatchA x dispatchB resolves to ONE case per concrete site (1 dfs inlined). Non-leaf inners
    // fall back to the non-inline flatMapCopyOne.
    // One pass: size the output from the FIRST inner (cnt * firstLen) so a uniform flatMap (the common case)
    // never grows or trims — only non-uniform inner sizes fall back to ensureCap growth.
    val flatMapOne = {
      def stepOf(kb: Kind, src: String): String =
        s"val inr = f($src); val ln = inr.length; out = ensureCap${kb.name}(out, off + ln); inr match { case lf: ${kb.name}Arr => System.arraycopy(lf.arr, 0, out, off, ln); case _ => flatMapCopyOne${kb.name}(inr, out, off) }; off += ln"
      def branch(ka: Kind, kb: Kind, src0: String, srcI: String): String = {
        val est = "{ val e = cnt * l0; if (e < 8) 8 else e }"
        val alloc = if kb.name == "Ref" then s"new Array[Object]($est)" else s"new Array[${kb.arr}]($est)"
        val copy0 = s"inr0 match { case lf: ${kb.name}Arr => System.arraycopy(lf.arr, 0, out, 0, l0); case _ => flatMapCopyOne${kb.name}(inr0, out, 0) }"
        s"{ val inr0 = f($src0); val l0 = inr0.length; out = $alloc; $copy0; off = l0; var i = 1; while (i < cnt) { ${stepOf(kb, srcI)}; i += 1 } }"
      }
      "summonFrom {\n" + opKinds
        .map { ka =>
          val inner = "summonFrom {\n" + opKinds
            .map { kb =>
              val outType = if kb.name == "Ref" then "Array[Object]" else s"Array[${kb.arr}]"
              val leafBranch = s"{ val sa = leaf.arr; ${branch(ka, kb, readVal(ka, "sa(0)"), readVal(ka, "sa(i)"))} }"
              val nodeBranch = branch(ka, kb, readVal(ka, s"${ka.lc}At(xs, 0)"), readVal(ka, s"${ka.lc}At(xs, i)"))
              s"          case rb: ${kb.name}Repr[B] => { if (cnt == 0) Empty.INSTANCE else { var out: $outType = null; var off = 0; xs match { case leaf: ${ka.name}Arr => $leafBranch; case _ => $nodeBranch }; if (off == out.length) new ${kb.name}Arr(out, off) else new ${kb.name}Arr(java.util.Arrays.copyOf(out, off), off) } }"
            }
            .mkString("\n") + "\n        }"
          s"      case r: ${ka.name}Repr[A] => $inner"
        }
        .mkString("\n") + "\n    }"
    }
    // single-pass unzip/unzip3: read each tuple ONCE, fill the 2/3 output arrays unboxed. Dispatch on the
    // component kinds (resolves to one case per concrete site). Source leaf fast-path / applyBoxed.
    def allocFor(k: Kind, rv: String): String = if k.name == "Ref" then s"new Array[Object](n)" else s"new Array[${k.arr}](n)"
    val unzipV = "summonFrom {\n" + opKinds
      .map { k1 =>
        val inner = "summonFrom {\n" + opKinds
          .map { k2 =>
            val fill = s"o1(i) = ${wr(k1, "r1.unwrap(t._1)")}; o2(i) = ${wr(k2, "r2.unwrap(t._2)")}"
            s"          case r2: ${k2.name}Repr[A2] => { val o1 = ${allocFor(k1, "r1")}; val o2 = ${allocFor(k2, "r2")}; xs match { case leaf: RefArr => { val sa = leaf.arr; var i = 0; while (i < n) { val t = ev(sa(i).asInstanceOf[A]); $fill; i += 1 } }; case _ => { var i = 0; while (i < n) { val t = ev((xs: FBase).applyBoxed(i).asInstanceOf[A]); $fill; i += 1 } } }; (new ${k1.name}Arr(o1, n), new ${k2.name}Arr(o2, n)) }"
          }
          .mkString("\n") + "\n        }"
        s"      case r1: ${k1.name}Repr[A1] => $inner"
      }
      .mkString("\n") + "\n    }"
    val unzip3V = "summonFrom {\n" + opKinds
      .map { k1 =>
        val m2 = "summonFrom {\n" + opKinds
          .map { k2 =>
            val m3 = "summonFrom {\n" + opKinds
              .map { k3 =>
                val fill = s"o1(i) = ${wr(k1, "r1.unwrap(t._1)")}; o2(i) = ${wr(k2, "r2.unwrap(t._2)")}; o3(i) = ${wr(k3, "r3.unwrap(t._3)")}"
                s"              case r3: ${k3.name}Repr[A3] => { val o1 = ${allocFor(k1, "r1")}; val o2 = ${allocFor(k2, "r2")}; val o3 = ${allocFor(k3, "r3")}; xs match { case leaf: RefArr => { val sa = leaf.arr; var i = 0; while (i < n) { val t = ev(sa(i).asInstanceOf[A]); $fill; i += 1 } }; case _ => { var i = 0; while (i < n) { val t = ev((xs: FBase).applyBoxed(i).asInstanceOf[A]); $fill; i += 1 } } }; (new ${k1.name}Arr(o1, n), new ${k2.name}Arr(o2, n), new ${k3.name}Arr(o3, n)) }"
              }
              .mkString("\n") + "\n            }"
            s"          case r2: ${k2.name}Repr[A2] => $m3"
          }
          .mkString("\n") + "\n        }"
        s"      case r1: ${k1.name}Repr[A1] => $m2"
      }
      .mkString("\n") + "\n    }"
    // zip / zipWithIndex: read both operands UNBOXED (leaf fast-path + <kind>At fallback) into a RefArr of
    // tuples. For primitive×primitive we name the stdlib @specialized Tuple2 directly (Tuple2$mcXY$sp), which
    // stores the two values unboxed — Scala 3 no longer picks it itself, so a uniform-int zip never boxes the
    // elements into Integers; only the tuple object is allocated.
    def mkT(ka: Kind, kb: Kind, v1: String, v2: String): String =
      if (ka.isPrim && kb.isPrim) s"new scala.Tuple2$$mc${ka.specCh}${kb.specCh}$$sp($v1, $v2)"
      else s"new scala.Tuple2(${ka.box(v1)}, ${kb.box(v2)})"
    val zipV = "summonFrom {\n" + opKinds
      .map { ka =>
        val inner = "summonFrom {\n" + opKinds
          .map { kb =>
            val fast =
              s"val ax = xs.asInstanceOf[${ka.name}Arr].arr; val ay = that.asInstanceOf[${kb.name}Arr].arr; while (i < n) { out(i) = ${mkT(ka, kb, "ax(i)", "ay(i)")}; i += 1 }"
            val slow = s"while (i < n) { out(i) = ${mkT(ka, kb, s"${ka.lc}At(xs, i)", s"${kb.lc}At(that, i)")}; i += 1 }"
            s"          case rb: ${kb.name}Repr[B] => { val out = new Array[Object](n); var i = 0; if (xs.isInstanceOf[${ka.name}Arr] && that.isInstanceOf[${kb.name}Arr]) { $fast } else { $slow }; new RefArr(out, n) }"
          }
          .mkString("\n") + "\n        }"
        s"      case r: ${ka.name}Repr[A] => $inner"
      }
      .mkString("\n") + "\n    }"
    def mkTIdx(ka: Kind, v: String, idx: String): String =
      if (ka.isPrim) s"new scala.Tuple2$$mc${ka.specCh}I$$sp($v, $idx)"
      else s"new scala.Tuple2($v, ${opKinds.head.box(idx)})" // index is Int
    val zipIdxV = "summonFrom {\n" + opKinds
      .map { ka =>
        val fast = s"val ax = xs.asInstanceOf[${ka.name}Arr].arr; while (i < n) { out(i) = ${mkTIdx(ka, "ax(i)", "i")}; i += 1 }"
        val slow = s"while (i < n) { out(i) = ${mkTIdx(ka, s"${ka.lc}At(xs, i)", "i")}; i += 1 }"
        s"      case r: ${ka.name}Repr[A] => { val out = new Array[Object](n); var i = 0; if (xs.isInstanceOf[${ka.name}Arr]) { $fast } else { $slow }; new RefArr(out, n) }"
      }
      .mkString("\n") + "\n    }"
    // shared backbone for corresponds/startsWith/endsWith: walk xs[xsOff+i] vs that[i] for i in [0,m), calling
    // pred (continue while true). 2D dispatch on both operand kinds + leaf+leaf fast-path reading both arrays
    // unboxed (<kind>At fallback for trees) — kills the per-index applyAt O(n·depth) and the per-element match.
    val matchAll2V = "summonFrom {\n" + opKinds
      .map { ka =>
        val inner = "summonFrom {\n" + opKinds
          .map { kb =>
            val rdB = (e: String) => if kb.name == "Ref" then s"r2.wrap($e.asInstanceOf[B])" else s"r2.wrap($e)"
            val fast =
              s"val xa = xs.asInstanceOf[${ka.name}Arr].arr; val ta = that.asInstanceOf[${kb.name}Arr].arr; while (i < m && pred(${readVal(ka, "xa(i + xsOff)")}, ${rdB("ta(i)")})) i += 1"
            val slow = s"while (i < m && pred(${readVal(ka, s"${ka.lc}At(xs, i + xsOff)")}, ${rdB(s"${kb.lc}At(that, i)")})) i += 1"
            s"          case r2: ${kb.name}Repr[B] => { var i = 0; if (xs.isInstanceOf[${ka.name}Arr] && that.isInstanceOf[${kb.name}Arr]) { $fast } else { $slow }; i == m }"
          }
          .mkString("\n") + "\n        }"
        s"      case r: ${ka.name}Repr[A] => $inner"
      }
      .mkString("\n") + "\n    }"
    val updated = dispatchB(k => s"new ${k.name}Updated(xs, index, ${wr(k, "r.unwrap(elem)")})")
    val append = dispatchB(k => s"new ${k.name}Append(xs, r.unwrap(elem))")
    val prepend = dispatchA(k => s"new ${k.name}Prepend(r.unwrap(elem), xs)")
    val padTo = dispatchB(k => s"if (len <= xs.length) xs else new ${k.name}Pad(xs, len, ${wr(k, "r.unwrap(elem)")})")
    // Sort on FArray's own representation: materialize the kind array ONCE, stable-sort an int[] index
    // array (no Vector, no boxed indices), then permute into a fresh leaf. sortWith's comparator is inline
    // (fully unboxed); sorted/sortBy box only per ord comparison.
    // sortWith/sorted: Ref arrays use java.util.Arrays.sort (TimSort — stable, run-detecting, no boxing on
    // Object[]); primitive arrays keep the unboxed mergesort (a boxed-Integer TimSort would be slower).
    def sortDirect(k: Kind, ltXY: String, ltYX: String): String =
      if k.name == "Ref" then
        s"{ val vals = materializeRef(xs); val n = vals.length; if (n < 2) xs else { java.util.Arrays.sort(vals, ((x: Object, y: Object) => { if ($ltXY) -1 else if ($ltYX) 1 else 0 }): java.util.Comparator[Object]); new RefArr(vals, n) } }"
      else s"{ val vals = materialize${k.name}(xs); val n = vals.length; if (n < 2) xs else new ${k.name}Arr(sort${k.name}(vals, n, (x, y) => $ltXY), n) }"
    val sortWith = dispatchA(k => sortDirect(k, s"lt(${readVal(k, "x")}, ${readVal(k, "y")})", s"lt(${readVal(k, "y")}, ${readVal(k, "x")})"))
    // sorted has an Ordering, which IS a Comparator -> for Ref hand it straight to Arrays.sort (1 compare per
    // comparison; the lt-comparator would do up to 2). Primitives keep the unboxed natural mergesort.
    // natural primitive orderings -> hand the materialised array straight to java.util.Arrays.sort
    // (dual-pivot, no boxing). Stability is irrelevant for primitives. Double is excluded: the implicit
    // Ordering[Double] is IEEE (NaN handling differs from Arrays.sort's total order), so it keeps the mergesort.
    val sortedNat = Map("Int" -> "scala.math.Ordering.Int", "Long" -> "scala.math.Ordering.Long")
    val sortedV = dispatchA(k =>
      if k.name == "Ref" then
        s"{ val vals = materializeRef(xs); val n = vals.length; if (n < 2) xs else { java.util.Arrays.sort(vals, ord.asInstanceOf[java.util.Comparator[Object]]); new RefArr(vals, n) } }"
      else {
        val merge = s"new ${k.name}Arr(sort${k.name}(vals, n, (x, y) => ord.lt(${readVal(k, "x")}, ${readVal(k, "y")})), n)"
        val body = sortedNat.get(k.name) match {
          case Some(nat) => s"if (ord.asInstanceOf[AnyRef] eq $nat) { java.util.Arrays.sort(vals); new ${k.name}Arr(vals, n) } else $merge"
          case None      => merge
        }
        s"{ val vals = materialize${k.name}(xs); val n = vals.length; if (n < 2) xs else $body }"
      }
    )
    // sortBy: keys differ from values -> sort an UNBOXED int[] index by the materialized keys, then permute.
    // (Java's Arrays.sort can't sort an int[] by a comparator without boxing to Integer[], which is slower
    // than this — Java TimSort only helps the direct Ref element sorts above, where the array IS Object[].)
    val sortByV = dispatchA(k =>
      s"{ val vals = materialize${k.name}(xs); val n = vals.length; if (n < 2) xs else { val keys = mapImpl[A, B](xs)(f); val idx = new Array[Int](n); var t = 0; while (t < n) { idx(t) = t; t += 1 }; val sidx = sortInt(idx, n, (ii, jj) => ord.lt(applyAtImpl[B](keys, ii), applyAtImpl[B](keys, jj))); val out = ${allocPlain(k)}; var p = 0; while (p < n) { out(p) = vals(sidx(p)); p += 1 }; new ${k.name}Arr(out, n) } }"
    )
    val emptyB = dispatchA(k => s"Empty.INSTANCE")
    val tabulate = dispatchA(k =>
      s"if (n <= 0) Empty.INSTANCE else { val out = ${alloc(k, "r")}; var i = 0; while (i < n) { out(i) = ${wr(k, "r.unwrap(f(i))")}; i += 1 }; new ${k.name}Arr(out, n) }"
    )
    val applyVar = dispatchA(k =>
      s"if (as.isEmpty) Empty.INSTANCE else { val n = as.length; val out = ${alloc(k, "r")}; var i = 0; while (i < n) { out(i) = ${wr(k, "r.unwrap(as(i))")}; i += 1 }; new ${k.name}Arr(out, n) }"
    )
    val fromArr = dispatchA(k => s"new ${k.name}Arr(as.asInstanceOf[Array[${k.arr}]], as.length)")
    // small-arity construction without varargs/Seq/boxing (FArray(a, b) etc.) — the hot path inside flatMap
    def allocN(k: Kind, n: Int): String = if k.name == "Ref" then s"new Array[Object]($n)" else s"new Array[${k.arr}]($n)"
    val fromValues1 = dispatchA(k => s"new ${k.name}One(${wr(k, "r.unwrap(a)")})")
    val fromValues2 =
      dispatchA(k => s"{ val out = ${allocN(k, 2)}; out(0) = ${wr(k, "r.unwrap(a)")}; out(1) = ${wr(k, "r.unwrap(b)")}; new ${k.name}Arr(out, 2) }")
    val fromValues3 = dispatchA(k =>
      s"{ val out = ${allocN(k, 3)}; out(0) = ${wr(k, "r.unwrap(a)")}; out(1) = ${wr(k, "r.unwrap(b)")}; out(2) = ${wr(k, "r.unwrap(c)")}; new ${k.name}Arr(out, 3) }"
    )

    s"""package farray
       |
       |import scala.compiletime.summonFrom
       |
       |// GENERATED by GenCores — do not edit. Per-kind specialized combinator implementations.
       |// Unboxed primitive comparators (SAM) for the non-inline sorts.
       |$lessTraits
       |// Per-kind leaf-run consumers for the non-inline dfsC traversals.
       |$dfsConsumers
       |$cursors
       |object FArrayOps {
       |$dfsC
       |$ats
       |$mat
       |$flatMapCopyOne
       |$sortArr
       |
       |  inline def emptyImpl[A]: FBase = $emptyB
       |  inline def applyImpl[A](as: Seq[A]): FBase = $applyVar
       |  inline def fromValues1[A](a: A): FBase = $fromValues1
       |  inline def fromValues2[A](a: A, b: A): FBase = $fromValues2
       |  inline def fromValues3[A](a: A, b: A, c: A): FBase = $fromValues3
       |  inline def tabulateImpl[A](n: Int)(inline f: Int => A): FBase = $tabulate
       |  inline def fromArrayImpl[A](as: Array[A]): FBase = $fromArr
       |  inline def foldLeftImpl[A, Z](xs: FBase, z: Z)(inline op: (Z, A) => Z): Z = { val n = xs.length; if (n == 0) z else if (n == 1) op(z, applyAtImpl[A](xs, 0)) else $foldLeft }
       |  inline def foldRightImpl[A, Z](xs: FBase, z: Z)(inline op: (A, Z) => Z): Z = { val n = xs.length; if (n == 0) z else if (n == 1) op(applyAtImpl[A](xs, 0), z) else $foldRightV }
       |  inline def iteratorImpl[A](xs: FBase): Iterator[A] = ($iteratorV).asInstanceOf[Iterator[A]]
       |  inline def countImpl[A](xs: FBase)(inline p: A => Boolean): Int = { val n = xs.length; if (n == 0) 0 else if (n == 1) (if (p(applyAtImpl[A](xs, 0))) 1 else 0) else $countV }
       |  inline def foreachImpl[A](xs: FBase)(inline f: A => Unit): Unit = { val n = xs.length; if (n == 1) f(applyAtImpl[A](xs, 0)) else if (n > 1) { $foreach } }
       |  inline def foreachWhileImpl[A](xs: FBase)(inline f: A => Boolean): Unit = { val n = xs.length; if (n == 1) { f(applyAtImpl[A](xs, 0)); () } else if (n > 1) { $foreachWhileV } }
       |  inline def existsImpl[A](xs: FBase)(inline p: A => Boolean): Boolean = { val n = xs.length; n != 0 && (if (n == 1) p(applyAtImpl[A](xs, 0)) else { $existsV }) }
       |  inline def forallImpl[A](xs: FBase)(inline p: A => Boolean): Boolean = { val n = xs.length; n == 0 || (if (n == 1) p(applyAtImpl[A](xs, 0)) else { $forallV }) }
       |  inline def findImpl[A](xs: FBase)(inline p: A => Boolean): Option[A] = { val n = xs.length; if (n == 0) None else if (n == 1) { val e = applyAtImpl[A](xs, 0); if (p(e)) Some(e) else None } else { $findV } }
       |  inline def indexWhereImpl[A](xs: FBase)(inline p: A => Boolean): Int = { val n = xs.length; if (n == 0) -1 else if (n == 1) (if (p(applyAtImpl[A](xs, 0))) 0 else -1) else { $indexWhereV } }
       |  inline def indexOfImpl[A, B](xs: FBase, elem: B): Int = { val n = xs.length; if (n == 0) -1 else if (n == 1) (if (applyAtImpl[A](xs, 0) == elem) 0 else -1) else $indexOfV }
       |  inline def collectFirstImpl[A, B](xs: FBase)(pf: PartialFunction[A, B]): Option[B] = { val n = xs.length; if (n == 0) None else if (n == 1) pf.lift(applyAtImpl[A](xs, 0)) else $collectFirstV }
       |  inline def prefixLengthImpl[A](xs: FBase)(inline p: A => Boolean): Int = { val n = xs.length; if (n == 0) 0 else if (n == 1) (if (p(applyAtImpl[A](xs, 0))) 1 else 0) else $prefixLenV }
       |  inline def mapImpl[A, B](xs: FBase)(inline f: A => B): FBase = {
       |    val n = xs.length
       |    if (n == 0) emptyImpl[B] else if (n == 1) fromValues1[B](f(applyAtImpl[A](xs, 0))) else { $mapM }
       |  }
       |  inline def filterImpl[A](xs: FBase)(inline p: A => Boolean): FBase = {
       |    val n = xs.length
       |    if (n == 0) emptyImpl[A] else if (n == 1) { val e = applyAtImpl[A](xs, 0); if (p(e)) fromValues1[A](e) else emptyImpl[A] } else { $filter }
       |  }
       |  inline def containsImpl[A](xs: FBase, elem: A): Boolean = { val n = xs.length; if (n == 0) false else if (n == 1) (applyAtImpl[A](xs, 0) == elem) else $contains }
       |  inline def mapConserveImpl[A](xs: FBase)(inline f: A => A): FBase = { val n = xs.length; if (n == 0) xs else if (n == 1) { val e = applyAtImpl[A](xs, 0); val r = f(e); if (r.asInstanceOf[AnyRef] eq e.asInstanceOf[AnyRef]) xs else fromValues1[A](r) } else $mapConserve }
       |  inline def unzipImpl[A, A1, A2](xs: FBase)(ev: A <:< (A1, A2)): (FBase, FBase) = { val n = xs.length; if (n == 0) (Empty.INSTANCE, Empty.INSTANCE) else $unzipV }
       |  inline def unzip3Impl[A, A1, A2, A3](xs: FBase)(ev: A <:< (A1, A2, A3)): (FBase, FBase, FBase) = { val n = xs.length; if (n == 0) (Empty.INSTANCE, Empty.INSTANCE, Empty.INSTANCE) else $unzip3V }
       |  inline def zipImpl[A, B](xs: FBase, that: FBase): FBase = { val n = if (xs.length < that.length) xs.length else that.length; if (n == 0) Empty.INSTANCE else if (n == 1) fromValues1[(A, B)]((applyAtImpl[A](xs, 0), applyAtImpl[B](that, 0))) else { $zipV } }
       |  inline def zipWithIndexImpl[A](xs: FBase): FBase = { val n = xs.length; if (n == 0) Empty.INSTANCE else if (n == 1) fromValues1[(A, Int)]((applyAtImpl[A](xs, 0), 0)) else { $zipIdxV } }
       |  inline def matchAll2Impl[A, B](xs: FBase, xsOff: Int, that: FBase, m: Int)(inline pred: (A, B) => Boolean): Boolean = $matchAll2V
       |  inline def applyAtImpl[A](xs: FBase, i: Int): A = $applyAt
       |  inline def flatMapImpl[A, B](xs: FBase)(inline f: A => FBase): FBase = { val cnt = xs.length; if (cnt == 1) f(applyAtImpl[A](xs, 0)) else $flatMapOne }
       |  inline def updatedImpl[A, B](xs: FBase, index: Int, elem: B): FBase = if (xs.length == 1 && index == 0) fromValues1[B](elem) else $updated
       |  inline def appendImpl[A, B](xs: FBase, elem: B): FBase = if (xs.length == 0) fromValues1[B](elem) else $append
       |  inline def prependImpl[A](elem: A, xs: FBase): FBase = if (xs.length == 0) fromValues1[A](elem) else $prepend
       |  inline def padToImpl[A, B](xs: FBase, len: Int, elem: B): FBase = $padTo
       |  inline def sortWithImpl[A](xs: FBase)(inline lt: (A, A) => Boolean): FBase = $sortWith
       |  inline def sortedImpl[A, B >: A](xs: FBase)(using ord: Ordering[B]): FBase = $sortedV
       |  inline def sortByImpl[A, B](xs: FBase)(inline f: A => B)(using ord: Ordering[B]): FBase = $sortByV
       |}
       |""".stripMargin
  }

  private def fbase: String = {
    val leaves = prims.flatMap(p => List(s"${p.name}Arr", s"${p.name}Append", s"${p.name}Prepend"))
    val permits =
      (List("Empty") ++ leaves ++ List("RefArr", "RefAppend", "RefPrepend", "Concat", "RangeNode", "ReverseNode", "SliceNode") ++ padKinds.map(_._1 + "Pad") ++ padKinds.map(
        _._1 + "Updated"
      ) ++ padKinds.map(_._1 + "One")).mkString(", ")
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit.
       |public sealed abstract class FBase permits $permits {
       |    public final int length;
       |    protected FBase(int length) { this.length = length; }
       |
       |    public abstract Object applyBoxed(int i);
       |    public abstract FBase take(int n);
       |    public abstract FBase drop(int n);
       |    public abstract FBase slice(int from, int until);
       |    public abstract FBase reverse();
       |    public abstract FBase init();
       |
       |    /** O(1) concat: builds a Concat tree node; never casts, so heterogeneous kinds are safe. */
       |    public final FBase concat(FBase that) {
       |        if (that.length == 0) return this;
       |        if (this.length == 0) return that;
       |        return new Concat(this, that);
       |    }
       |}
       |""".stripMargin
  }

  private def primCore(p: Prim): String = {
    val cls = s"${p.name}Arr"
    s"""package farray;
       |
       |import java.util.Arrays;
       |
       |// GENERATED by GenCores — do not edit. ${p.jt}[]-backed specialized leaf.
       |public final class $cls extends FBase {
       |    public final ${p.jt}[] arr;
       |    public $cls(${p.jt}[] arr, int length) { super(length); this.arr = arr; }
       |
       |    @Override public Object applyBoxed(int i) { return ${p.boxed}.valueOf(arr[i]); }
       |
       |    @Override public FBase take(int n) { int m = n < 0 ? 0 : (n > length ? length : n); return m == 0 ? Empty.INSTANCE : (m == length ? this : new SliceNode(this, 0, m)); }
       |    @Override public FBase drop(int n) { int d = n < 0 ? 0 : (n > length ? length : n); return d == 0 ? this : (d == length ? Empty.INSTANCE : new SliceNode(this, d, length - d)); }
       |    @Override public FBase slice(int from, int until) { int lo = from < 0 ? 0 : from, hi = until > length ? length : until; if (lo >= hi) return Empty.INSTANCE; return (lo == 0 && hi == length) ? this : new SliceNode(this, lo, hi - lo); }
       |    @Override public FBase reverse() { return length < 2 ? this : new ReverseNode(this); }
       |    @Override public FBase init() { return new $cls(arr, length - 1); }
       |
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object obj) {
       |        if (this == obj) return true;
       |        if (!(obj instanceof $cls)) return Concat.elementwiseEquals(this, obj);
       |        $cls other = ($cls) obj;
       |        if (other.length != length) return false;
       |        for (int i = 0; i < length; i++) if (arr[i] != other.arr[i]) return false;
       |        return true;
       |    }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin
  }

  private def refArr: String =
    s"""package farray;
       |
       |import java.util.Arrays;
       |
       |// GENERATED by GenCores — do not edit. Object[]-backed leaf for reference element types.
       |public final class RefArr extends FBase {
       |    public final Object[] arr;
       |    public RefArr(Object[] arr, int length) { super(length); this.arr = arr; }
       |
       |    @Override public Object applyBoxed(int i) { return arr[i]; }
       |
       |    @Override public FBase take(int n) { int m = n < 0 ? 0 : (n > length ? length : n); return m == 0 ? Empty.INSTANCE : (m == length ? this : new SliceNode(this, 0, m)); }
       |    @Override public FBase drop(int n) { int d = n < 0 ? 0 : (n > length ? length : n); return d == 0 ? this : (d == length ? Empty.INSTANCE : new SliceNode(this, d, length - d)); }
       |    @Override public FBase slice(int from, int until) { int lo = from < 0 ? 0 : from, hi = until > length ? length : until; if (lo >= hi) return Empty.INSTANCE; return (lo == 0 && hi == length) ? this : new SliceNode(this, lo, hi - lo); }
       |    @Override public FBase reverse() { return length < 2 ? this : new ReverseNode(this); }
       |    @Override public FBase init() { return new RefArr(arr, length - 1); }
       |
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object obj) {
       |        if (this == obj) return true;
       |        if (!(obj instanceof RefArr)) return Concat.elementwiseEquals(this, obj);
       |        RefArr other = (RefArr) obj;
       |        if (other.length != length) return false;
       |        for (int i = 0; i < length; i++) {
       |            Object x = arr[i], y = other.arr[i];
       |            if (x == null ? y != null : !x.equals(y)) return false;
       |        }
       |        return true;
       |    }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin

  private def concat: String =
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Tree node: O(1) concat, structural ops recurse (Java
       |// recursion is fine here — only the inline Scala combinators must avoid recursion to keep the
       |// element op spliced). Element traversal uses an explicit stack in the Scala combinators.
       |public final class Concat extends FBase {
       |    public final FBase left;
       |    public final FBase right;
       |    public Concat(FBase left, FBase right) {
       |        super(left.length + right.length);
       |        this.left = left;
       |        this.right = right;
       |    }
       |
       |    @Override public Object applyBoxed(int i) {
       |        return i < left.length ? left.applyBoxed(i) : right.applyBoxed(i - left.length);
       |    }
       |    @Override public FBase take(int n) {
       |        if (n <= 0) return left.take(0);
       |        if (n >= length) return this;
       |        if (n <= left.length) return left.take(n);
       |        return new Concat(left, right.take(n - left.length));
       |    }
       |    @Override public FBase drop(int n) {
       |        if (n <= 0) return this;
       |        if (n >= length) return right.drop(right.length);
       |        if (n >= left.length) return right.drop(n - left.length);
       |        return new Concat(left.drop(n), right);
       |    }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from;
       |        int hi = until > length ? length : until;
       |        if (lo >= hi) return left.take(0);
       |        return drop(lo).take(hi - lo);
       |    }
       |    @Override public FBase reverse() { return new Concat(right.reverse(), left.reverse()); }
       |    @Override public FBase init() { return take(length - 1); }

       |
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object obj) { return elementwiseEquals(this, obj); }
       |    @Override public String toString() { return render(this); }
       |
       |    /** Shared element-wise equality across any two cores (used when concrete kinds differ). */
       |    static boolean elementwiseEquals(FBase self, Object obj) {
       |        if (self == obj) return true;
       |        if (!(obj instanceof FBase)) return false;
       |        FBase other = (FBase) obj;
       |        if (other.length != self.length) return false;
       |        for (int i = 0; i < self.length; i++) {
       |            Object x = self.applyBoxed(i), y = other.applyBoxed(i);
       |            if (x == null ? y != null : !x.equals(y)) return false;
       |        }
       |        return true;
       |    }
       |    static String render(FBase self) {
       |        StringBuilder sb = new StringBuilder("FArray(");
       |        for (int i = 0; i < self.length; i++) { if (i != 0) sb.append(", "); sb.append(self.applyBoxed(i)); }
       |        return sb.append(')').toString();
       |    }
       |}
       |""".stripMargin

  /** Closed-form Int range — O(1) construct, O(1) index/take/drop/reverse, never materializes. Int kind only. */
  private def rangeNode: String =
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Lazy closed-form Int range node.
       |public final class RangeNode extends FBase {
       |    public final int start;
       |    public final int step;
       |    public RangeNode(int start, int step, int length) { super(length); this.start = start; this.step = step; }
       |    @Override public Object applyBoxed(int i) { return Integer.valueOf(start + i * step); }
       |    @Override public FBase take(int n) {
       |        int m = n < 0 ? 0 : (n > length ? length : n);
       |        return m == length ? this : (m == 0 ? Empty.INSTANCE : new RangeNode(start, step, m));
       |    }
       |    @Override public FBase drop(int n) {
       |        int d = n < 0 ? 0 : (n > length ? length : n);
       |        return d == 0 ? this : (d == length ? Empty.INSTANCE : new RangeNode(start + d * step, step, length - d));
       |    }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from, hi = until > length ? length : until;
       |        if (lo >= hi) return Empty.INSTANCE;
       |        return new RangeNode(start + lo * step, step, hi - lo);
       |    }
       |    @Override public FBase reverse() { return length < 2 ? this : new RangeNode(start + (length - 1) * step, -step, length); }
       |    @Override public FBase init() { return take(length - 1); }
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object o) { return Concat.elementwiseEquals(this, o); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin

  /** Lazy reverse — O(1) construct, shares the base; index/dfs read the base at the mirrored position. */
  private def reverseNode: String =
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Lazy reverse node (kind-agnostic; base shared).
       |public final class ReverseNode extends FBase {
       |    public final FBase base;
       |    public ReverseNode(FBase base) { super(base.length); this.base = base; }
       |    @Override public Object applyBoxed(int i) { return base.applyBoxed(length - 1 - i); }
       |    @Override public FBase take(int n) {
       |        int m = n < 0 ? 0 : (n > length ? length : n);
       |        if (m == 0) return base.take(0);
       |        return new ReverseNode(base.drop(length - m));
       |    }
       |    @Override public FBase drop(int n) {
       |        int d = n < 0 ? 0 : (n > length ? length : n);
       |        if (d == length) return base.take(0);
       |        return new ReverseNode(base.take(length - d));
       |    }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from, hi = until > length ? length : until;
       |        if (lo >= hi) return base.take(0);
       |        return drop(lo).take(hi - lo);
       |    }
       |    @Override public FBase reverse() { return base; }
       |    @Override public FBase init() { return take(length - 1); }
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object o) { return Concat.elementwiseEquals(this, o); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin

  /** Lazy slice — O(1) take/drop/slice as a window (base + offset) into the base; index reads base at offset+i. */
  private def sliceNode: String =
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Lazy slice/take/drop node (kind-agnostic window over a leaf base).
       |public final class SliceNode extends FBase {
       |    public final FBase base;
       |    public final int offset;
       |    public SliceNode(FBase base, int offset, int length) { super(length); this.base = base; this.offset = offset; }
       |    @Override public Object applyBoxed(int i) { return base.applyBoxed(offset + i); }
       |    @Override public FBase take(int n) { int m = n < 0 ? 0 : (n > length ? length : n); return m == length ? this : new SliceNode(base, offset, m); }
       |    @Override public FBase drop(int n) { int d = n < 0 ? 0 : (n > length ? length : n); return d == 0 ? this : new SliceNode(base, offset + d, length - d); }
       |    @Override public FBase slice(int from, int until) { int lo = from < 0 ? 0 : from, hi = until > length ? length : until; if (lo >= hi) return new SliceNode(base, offset, 0); return (lo == 0 && hi == length) ? this : new SliceNode(base, offset + lo, hi - lo); }
       |    @Override public FBase reverse() { return new ReverseNode(this); }
       |    @Override public FBase init() { return take(length - 1); }
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object o) { return Concat.elementwiseEquals(this, o); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin

  /** Ops-kinds (Int/Long/Double/Ref) for the per-kind lazy nodes that carry a primitive payload. */
  private val padKinds = List(("Int", "int", "Integer"), ("Long", "long", "Long"), ("Double", "double", "Double"), ("Ref", "Object", ""))

  /** padTo as a lazy node: base + targetLen + a constant filler. O(1) construct, O(depth) index — so range(1M).padTo(2M, x).last is O(1). For prims base is
    * always the same kind (B>:A, prims are final); RefPad reads its base via applyBoxed so an Int-base widened to a Ref pad still works.
    */
  private def padNode(name: String, jt: String, boxed: String): String =
    val boxedFiller = if boxed.isEmpty then "filler" else s"$boxed.valueOf(filler)"
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Lazy padTo node (base shared, constant filler).
       |public final class ${name}Pad extends FBase {
       |    public final FBase base;
       |    public final $jt filler;
       |    public ${name}Pad(FBase base, int targetLen, $jt filler) { super(targetLen); this.base = base; this.filler = filler; }
       |    @Override public Object applyBoxed(int i) { return i < base.length ? base.applyBoxed(i) : $boxedFiller; }
       |    @Override public FBase take(int n) { int m = n < 0 ? 0 : (n > length ? length : n); return m <= base.length ? base.take(m) : new ${name}Pad(base, m, filler); }
       |    @Override public FBase drop(int n) {
       |        int d = n < 0 ? 0 : (n > length ? length : n);
       |        if (d == 0) return this;
       |        if (d >= length) return base.take(0);
       |        if (d >= base.length) return new ${name}Pad(base.take(0), length - d, filler);
       |        return new ${name}Pad(base.drop(d), length - d, filler);
       |    }
       |    @Override public FBase slice(int from, int until) { int lo = from < 0 ? 0 : from, hi = until > length ? length : until; return lo >= hi ? base.take(0) : drop(lo).take(hi - lo); }
       |    @Override public FBase reverse() { return new ReverseNode(this); }
       |    @Override public FBase init() { return take(length - 1); }
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object o) { return Concat.elementwiseEquals(this, o); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin

  /** updated as a lazy node: base + a single overridden (index, elem). O(1) construct, O(depth) index. */
  private def updatedNode(name: String, jt: String, boxed: String): String =
    val boxedElem = if boxed.isEmpty then "elem" else s"$boxed.valueOf(elem)"
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Lazy updated node (base shared, one overridden element).
       |public final class ${name}Updated extends FBase {
       |    public final FBase base;
       |    public final int index;
       |    public final $jt elem;
       |    public ${name}Updated(FBase base, int index, $jt elem) { super(base.length); this.base = base; this.index = index; this.elem = elem; }
       |    @Override public Object applyBoxed(int i) { return i == index ? $boxedElem : base.applyBoxed(i); }
       |    @Override public FBase take(int n) { int m = n < 0 ? 0 : (n > length ? length : n); return m <= index ? base.take(m) : new ${name}Updated(base.take(m), index, elem); }
       |    @Override public FBase drop(int n) { int d = n < 0 ? 0 : (n > length ? length : n); return d > index ? base.drop(d) : new ${name}Updated(base.drop(d), index - d, elem); }
       |    @Override public FBase slice(int from, int until) { int lo = from < 0 ? 0 : from, hi = until > length ? length : until; return lo >= hi ? base.take(0) : drop(lo).take(hi - lo); }
       |    @Override public FBase reverse() { return new ReverseNode(this); }
       |    @Override public FBase init() { return take(length - 1); }
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object o) { return Concat.elementwiseEquals(this, o); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin

  /** Singleton node: one element held directly, no backing array. O(1) everything. */
  private def oneNode(name: String, jt: String, boxed: String): String =
    val boxedElem = if boxed.isEmpty then "elem" else s"$boxed.valueOf(elem)"
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Singleton: one element, no backing array.
       |public final class ${name}One extends FBase {
       |    public final $jt elem;
       |    public ${name}One($jt elem) { super(1); this.elem = elem; }
       |    @Override public Object applyBoxed(int i) { return $boxedElem; }
       |    @Override public FBase take(int n) { return n <= 0 ? Empty.INSTANCE : this; }
       |    @Override public FBase drop(int n) { return n <= 0 ? this : Empty.INSTANCE; }
       |    @Override public FBase slice(int from, int until) { return (from <= 0 && until >= 1) ? this : Empty.INSTANCE; }
       |    @Override public FBase reverse() { return this; }
       |    @Override public FBase init() { return Empty.INSTANCE; }
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object o) { return Concat.elementwiseEquals(this, o); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin

  /** The one empty sequence — kind-agnostic (no elements), a single shared instance. */
  private def emptyNode: String =
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. The single empty sequence (no elements, no kind).
       |public final class Empty extends FBase {
       |    public static final Empty INSTANCE = new Empty();
       |    private Empty() { super(0); }
       |    @Override public Object applyBoxed(int i) { throw new IndexOutOfBoundsException(Integer.toString(i)); }
       |    @Override public FBase take(int n) { return this; }
       |    @Override public FBase drop(int n) { return this; }
       |    @Override public FBase slice(int from, int until) { return this; }
       |    @Override public FBase reverse() { return this; }
       |    @Override public FBase init() { return this; }
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object o) { return Concat.elementwiseEquals(this, o); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin

  /** Unboxed, order-dependent hash: dispatch on each node's runtime kind and hash raw primitives. Replaces the per-node applyBoxed loops (which boxed every
    * element). `rev` flips order for ReverseNode.
    */
  private def hashing: String = {
    def eh(p: Prim, e: String): String = p.name match
      case "Long"    => s"scala.runtime.Statics.longHash($e)"
      case "Double"  => s"scala.runtime.Statics.doubleHash($e)"
      case "Float"   => s"scala.runtime.Statics.floatHash($e)"
      case "Boolean" => s"($e ? 1231 : 1237)"
      case _         => e // Int/Short/Byte/Char: ## is the (widened) value
    val leafFill = prims
      .map(p =>
        s"""       |        if (node instanceof ${p.name}Arr a) { if (rev) for (int i = a.length - 1; i >= 0; i--) hs[pos++] = ${eh(
            p,
            "a.arr[i]"
          )}; else for (int i = 0; i < a.length; i++) hs[pos++] = ${eh(p, "a.arr[i]")}; return pos; }"""
      )
      .mkString("\n")
    val appendFill = prims
      .map(p =>
        s"""       |        if (node instanceof ${p.name}Append ap) { if (rev) { hs[pos++] = ${eh(
            p,
            "ap.elem"
          )}; return fill(ap.base, true, hs, pos); } else { pos = fill(ap.base, false, hs, pos); hs[pos++] = ${eh(p, "ap.elem")}; return pos; } }"""
      )
      .mkString("\n")
    val prependFill = prims
      .map(p =>
        s"""       |        if (node instanceof ${p.name}Prepend pp) { if (rev) { pos = fill(pp.base, true, hs, pos); hs[pos++] = ${eh(
            p,
            "pp.elem"
          )}; return pos; } else { hs[pos++] = ${eh(p, "pp.elem")}; return fill(pp.base, false, hs, pos); } }"""
      )
      .mkString("\n")
    val padFill = padKinds
      .map { case (name, _, _) =>
        val fh = name match
          case "Long"   => "scala.runtime.Statics.longHash(pad.filler)"
          case "Double" => "scala.runtime.Statics.doubleHash(pad.filler)"
          case "Ref"    => "scala.runtime.Statics.anyHash(pad.filler)"
          case _        => "pad.filler"
        s"""       |        if (node instanceof ${name}Pad pad) { int extra = pad.length - pad.base.length; if (rev) { for (int i = 0; i < extra; i++) hs[pos++] = $fh; return fill(pad.base, true, hs, pos); } else { pos = fill(pad.base, false, hs, pos); for (int i = 0; i < extra; i++) hs[pos++] = $fh; return pos; } }"""
      }
      .mkString("\n")
    val updatedFill = padKinds
      .map { case (name, _, _) =>
        val eh2 = name match
          case "Long"   => "scala.runtime.Statics.longHash(u.elem)"
          case "Double" => "scala.runtime.Statics.doubleHash(u.elem)"
          case "Ref"    => "scala.runtime.Statics.anyHash(u.elem)"
          case _        => "u.elem"
        s"""       |        if (node instanceof ${name}Updated u) { int start = pos; pos = fill(u.base, rev, hs, pos); hs[rev ? (start + u.length - 1 - u.index) : (start + u.index)] = $eh2; return pos; }"""
      }
      .mkString("\n")
    val oneFill = padKinds
      .map { case (name, _, _) =>
        val eh2 = name match
          case "Long"   => "scala.runtime.Statics.longHash(o.elem)"
          case "Double" => "scala.runtime.Statics.doubleHash(o.elem)"
          case "Ref"    => "scala.runtime.Statics.anyHash(o.elem)"
          case _        => "o.elem"
        s"""       |        if (node instanceof ${name}One o) { hs[pos] = $eh2; return pos + 1; }"""
      }
      .mkString("\n")
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Hash byte-for-byte equal to Scala Seq.hashCode (List/Vector):
       |// collect each element's ## (unboxed, via scala.runtime.Statics) into an int[], then run MurmurHash3's
       |// ordered hash INCLUDING its arithmetic-progression optimisation (a constant-stride hash sequence ->
       |// rangeHash). A standalone RangeNode hashes in O(1) via rangeHash (no million-element walk). The int[]
       |// holds primitive element-hashes — no element is ever boxed.
       |final class Hashing {
       |    private static final int SEED = "Seq".hashCode();
       |    static int hashOf(FBase node) {
       |        if (node instanceof RangeNode rg) {
       |            if (rg.length == 0) return finalizeHash(SEED, 0);
       |            if (rg.length == 1) return finalizeHash(mix(SEED, rg.start), 1);
       |            return rangeHash(rg.start, rg.step, rg.start + (rg.length - 1) * rg.step, SEED);
       |        }
       |        int[] hs = new int[node.length];
       |        fill(node, false, hs, 0);
       |        return ordered(hs);
       |    }
       |    private static int mix(int h, int d) { return scala.util.hashing.MurmurHash3$$.MODULE$$.mix(h, d); }
       |    private static int finalizeHash(int h, int n) { return scala.util.hashing.MurmurHash3$$.MODULE$$.finalizeHash(h, n); }
       |    private static int rangeHash(int start, int step, int last, int seed) { return scala.util.hashing.MurmurHash3$$.MODULE$$.rangeHash(start, step, last, seed); }
       |    /** Exactly scala.util.hashing.MurmurHash3.orderedHash, hoisted to an int[] of element-hashes. */
       |    private static int ordered(int[] h) {
       |        int n = h.length;
       |        if (n == 0) return finalizeHash(SEED, 0);
       |        if (n == 1) return finalizeHash(mix(SEED, h[0]), 1);
       |        int diff = h[1] - h[0];
       |        boolean isRange = true;
       |        for (int i = 2; i < n; i++) if (h[i] - h[i - 1] != diff) { isRange = false; break; }
       |        if (isRange) return rangeHash(h[0], diff, h[n - 1], SEED);
       |        int acc = SEED;
       |        for (int i = 0; i < n; i++) acc = mix(acc, h[i]);
       |        return finalizeHash(acc, n);
       |    }
       |    /** Append each element's ## to hs in sequence order (rev flips it); returns the next free index. */
       |    private static int fill(FBase node, boolean rev, int[] hs, int pos) {
       |        if (node instanceof Empty) return pos;
$leafFill
       |        if (node instanceof RefArr a) { if (rev) for (int i = a.length - 1; i >= 0; i--) hs[pos++] = scala.runtime.Statics.anyHash(a.arr[i]); else for (int i = 0; i < a.length; i++) hs[pos++] = scala.runtime.Statics.anyHash(a.arr[i]); return pos; }
       |        if (node instanceof Concat c) { if (rev) { pos = fill(c.right, true, hs, pos); return fill(c.left, true, hs, pos); } else { pos = fill(c.left, false, hs, pos); return fill(c.right, false, hs, pos); } }
$appendFill
$prependFill
       |        if (node instanceof RefAppend ap) { if (rev) { hs[pos++] = scala.runtime.Statics.anyHash(ap.elem); return fill(ap.base, true, hs, pos); } else { pos = fill(ap.base, false, hs, pos); hs[pos++] = scala.runtime.Statics.anyHash(ap.elem); return pos; } }
       |        if (node instanceof RefPrepend pp) { if (rev) { pos = fill(pp.base, true, hs, pos); hs[pos++] = scala.runtime.Statics.anyHash(pp.elem); return pos; } else { hs[pos++] = scala.runtime.Statics.anyHash(pp.elem); return fill(pp.base, false, hs, pos); } }
       |        if (node instanceof ReverseNode r) { return fill(r.base, !rev, hs, pos); }
       |        if (node instanceof SliceNode s) { int[] tmp = new int[s.base.length]; fill(s.base, false, tmp, 0); if (rev) for (int i = s.length - 1; i >= 0; i--) hs[pos++] = tmp[s.offset + i]; else for (int i = 0; i < s.length; i++) hs[pos++] = tmp[s.offset + i]; return pos; }
$padFill
$updatedFill
$oneFill
       |        if (node instanceof RangeNode rg) { if (rev) for (int i = rg.length - 1; i >= 0; i--) hs[pos++] = rg.start + i * rg.step; else for (int i = 0; i < rg.length; i++) hs[pos++] = rg.start + i * rg.step; return pos; }
       |        for (int i = 0; i < node.length; i++) hs[pos++] = scala.runtime.Statics.anyHash(node.applyBoxed(rev ? node.length - 1 - i : i));
       |        return pos;
       |    }
       |}
       |""".stripMargin
  }

  private def primAppend(p: Prim): String = {
    val cls = s"${p.name}Append"
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Unary append node (base + one ${p.jt}, base shared).
       |public final class $cls extends FBase {
       |    public final FBase base;
       |    public final ${p.jt} elem;
       |    public $cls(FBase base, ${p.jt} elem) { super(base.length + 1); this.base = base; this.elem = elem; }
       |    @Override public Object applyBoxed(int i) { return i < base.length ? base.applyBoxed(i) : ${p.boxed}.valueOf(elem); }
       |    @Override public FBase take(int n) { return n >= length ? this : base.take(n); }
       |    @Override public FBase drop(int n) {
       |        if (n <= 0) return this;
       |        if (n >= length) return base.take(0);
       |        return new $cls(base.drop(n), elem);
       |    }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from; int hi = until > length ? length : until;
       |        if (lo >= hi) return base.take(0);
       |        return drop(lo).take(hi - lo);
       |    }
       |    @Override public FBase reverse() { return new ${p.name}Prepend(elem, base.reverse()); }
       |    @Override public FBase init() { return base; }
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object obj) { return Concat.elementwiseEquals(this, obj); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin
  }

  private def primPrepend(p: Prim): String = {
    val cls = s"${p.name}Prepend"
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Unary prepend node (one ${p.jt} + base, base shared).
       |public final class $cls extends FBase {
       |    public final ${p.jt} elem;
       |    public final FBase base;
       |    public $cls(${p.jt} elem, FBase base) { super(base.length + 1); this.elem = elem; this.base = base; }
       |    @Override public Object applyBoxed(int i) { return i == 0 ? ${p.boxed}.valueOf(elem) : base.applyBoxed(i - 1); }
       |    @Override public FBase take(int n) {
       |        if (n <= 0) return base.take(0);
       |        if (n >= length) return this;
       |        return new $cls(elem, base.take(n - 1));
       |    }
       |    @Override public FBase drop(int n) {
       |        if (n <= 0) return this;
       |        if (n >= length) return base.take(0);
       |        return n == 1 ? base : base.drop(n - 1);
       |    }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from; int hi = until > length ? length : until;
       |        if (lo >= hi) return base.take(0);
       |        return drop(lo).take(hi - lo);
       |    }
       |    @Override public FBase reverse() { return new ${p.name}Append(base.reverse(), elem); }
       |    @Override public FBase init() { return take(length - 1); }
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object obj) { return Concat.elementwiseEquals(this, obj); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin
  }

  private def refUnary(kind: String): String = {
    val cls = s"Ref$kind"
    val isAppend = kind == "Append"
    val fields = if isAppend then "public final FBase base;\n    public final Object elem;"
    else "public final Object elem;\n    public final FBase base;"
    val ctorArgs = if isAppend then "FBase base, Object elem" else "Object elem, FBase base"
    val ctorBody = if isAppend then "this.base = base; this.elem = elem;" else "this.elem = elem; this.base = base;"
    val applyB = if isAppend then "i < base.length ? base.applyBoxed(i) : elem" else "i == 0 ? elem : base.applyBoxed(i - 1)"
    val take = if isAppend then "return n >= length ? this : base.take(n);"
    else "if (n <= 0) return base.take(0); if (n >= length) return this; return new RefPrepend(elem, base.take(n - 1));"
    val drop = if isAppend then "if (n <= 0) return this; if (n >= length) return base.take(0); return new RefAppend(base.drop(n), elem);"
    else "if (n <= 0) return this; if (n >= length) return base.take(0); return n == 1 ? base : base.drop(n - 1);"
    val reverse = if isAppend then "return new RefPrepend(elem, base.reverse());" else "return new RefAppend(base.reverse(), elem);"
    val init = if isAppend then "return base;" else "return take(length - 1);"
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Unary $kind node for reference elements (base shared).
       |public final class $cls extends FBase {
       |    $fields
       |    public $cls($ctorArgs) { super(base.length + 1); $ctorBody }
       |    @Override public Object applyBoxed(int i) { return $applyB; }
       |    @Override public FBase take(int n) { $take }
       |    @Override public FBase drop(int n) { $drop }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from; int hi = until > length ? length : until;
       |        if (lo >= hi) return base.take(0);
       |        return drop(lo).take(hi - lo);
       |    }
       |    @Override public FBase reverse() { $reverse }
       |    @Override public FBase init() { $init }
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object obj) { return Concat.elementwiseEquals(this, obj); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin
  }
}
