package farray

import bleep.*
import bleep.internal.FileUtils

import java.nio.file.Files

/**
 * Generates the sealed FArray core hierarchy: `FBase` (abstract storage-shuffling API + a concrete
 * O(1) `concat` that builds a `Concat` tree node) + one `<Name>Arr` leaf per primitive + the
 * `Object[]`-backed `RefArr` leaf + the `Concat` tree node. Wired as `farray`'s sourcegen.
 *
 * Element-touching combinators and element-insert ops (`:+`/`+:`/`updated`) live in Scala (inline,
 * specialized) — NOT here. Adding a primitive = one row in `prims`.
 */
object GenCores extends BleepCodegenScript("GenCores") {

  final case class Prim(name: String, jt: String, boxed: String)

  val prims: List[Prim] = List(
    Prim("Int", "int", "Integer"),
    Prim("Long", "long", "Long"),
    Prim("Double", "double", "Double"),
    Prim("Float", "float", "Float"),
    Prim("Short", "short", "Short"),
    Prim("Byte", "byte", "Byte"),
    Prim("Char", "char", "Character"),
    Prim("Boolean", "boolean", "Boolean")
  )

  override def run(started: Started, commands: Commands, targets: List[GenCores.Target], args: List[String]): Unit =
    targets.foreach { target =>
      val dir = target.sources.resolve("farray")
      FileUtils.deleteDirectory(target.sources)
      Files.createDirectories(dir)
      Files.writeString(dir.resolve("FBase.java"), fbase)
      Files.writeString(dir.resolve("RefArr.java"), refArr)
      Files.writeString(dir.resolve("RefAppend.java"), refUnary("Append"))
      Files.writeString(dir.resolve("RefPrepend.java"), refUnary("Prepend"))
      Files.writeString(dir.resolve("Concat.java"), concat)
      Files.writeString(dir.resolve("RangeNode.java"), rangeNode)
      Files.writeString(dir.resolve("ReverseNode.java"), reverseNode)
      Files.writeString(dir.resolve("SliceNode.java"), sliceNode)
      Files.writeString(dir.resolve("Hashing.java"), hashing)
      padKinds.foreach { case (name, jt, boxed) => Files.writeString(dir.resolve(s"${name}Pad.java"), padNode(name, jt, boxed)) }
      padKinds.foreach { case (name, jt, boxed) => Files.writeString(dir.resolve(s"${name}Updated.java"), updatedNode(name, jt, boxed)) }
      prims.foreach { p =>
        Files.writeString(dir.resolve(s"${p.name}Arr.java"), primCore(p))
        Files.writeString(dir.resolve(s"${p.name}Append.java"), primAppend(p))
        Files.writeString(dir.resolve(s"${p.name}Prepend.java"), primPrepend(p))
      }
      Files.writeString(dir.resolve("Repr.scala"), reprSrc)
      Files.writeString(dir.resolve("FArrayOps.scala"), farrayOps)
    }

  /** Unified array-representation evidence — subsumes primitive specialization, value-class/opaque
   *  unwrapping (Prim + inline wrap/unwrap), and reference ClassTag (RefRepr.ct). One per concrete A;
   *  absent for abstract A ⇒ summonFrom fails ⇒ compile error (specialize-or-fail). */
  private def reprSrc: String = {
    val subtraits = opKinds.map { k =>
      if k.name == "Ref" then "trait RefRepr[A] extends Repr[A] { type Prim = A; def ct: scala.reflect.ClassTag[A] }"
      else s"trait ${k.name}Repr[A] extends Repr[A] { type Prim = ${k.arr} }"
    }.mkString("\n")
    val givens = opKinds.map { k =>
      if k.name == "Ref" then
        "  given refRepr[A <: AnyRef](using c: scala.reflect.ClassTag[A]): RefRepr[A] with { def ct: scala.reflect.ClassTag[A] = c; inline def unwrap(a: A): A = a; inline def wrap(p: A): A = p }"
      else
        s"  given ${k.lc}Repr: ${k.name}Repr[${k.arr}] with { inline def unwrap(a: ${k.arr}): ${k.arr} = a; inline def wrap(p: ${k.arr}): ${k.arr} = p }"
    }.mkString("\n")
    s"""package farray
       |
       |// GENERATED by GenCores — do not edit.
       |sealed trait Repr[A] {
       |  type Prim
       |  inline def unwrap(a: A): Prim
       |  inline def wrap(p: Prim): A
       |}
       |$subtraits
       |
       |object Repr {
       |$givens
       |}
       |""".stripMargin
  }

  // ===== generated per-kind Scala combinators (the read×write matrix lives here, not hand-written) =====

  /** name=core prefix (Int/Long/Double/Ref); arr=Scala array elem type; pat=erasedValue pattern; dflt=zero. */
  final case class Kind(name: String, arr: String, pat: String, dflt: String) { def lc = name.toLowerCase }

  // Start with the common numeric kinds + reference; add rows here to cover more primitives.
  val opKinds: List[Kind] = List(
    Kind("Int", "Int", "Int", "0"),
    Kind("Long", "Long", "Long", "0L"),
    Kind("Double", "Double", "Double", "0.0"),
    Kind("Ref", "Object", "AnyRef", "null")
  )

  private val grow =
    "if (sp + 2 > stack.length) { val ns = stack.length * 2; stack = java.util.Arrays.copyOf(stack, ns); tail = java.util.Arrays.copyOf(tail, ns); isTail = java.util.Arrays.copyOf(isTail, ns) }"

  private def dfsDef(k: Kind): String = {
    // Lazy nodes emit unboxed via <kind>At per element (RangeNode is closed-form, Int only). onOne/At
    // return the raw primitive, so no boxing — only the boxed `applyBoxed` path (iterator) ever boxes.
    val rngCase = if k.name == "Int" then "\n       |        case rng: RangeNode => { val rn = rng.length; var ri = 0; while (ri < rn) { onOne(rng.start + ri * rng.step); ri += 1 } }" else ""
    // read the node's base directly (one dispatch), not through the node itself (which would re-dispatch per element)
    val padRead = if k.name == "Ref" then "pad.base.applyBoxed(pi)" else s"${k.lc}At(pad.base, pi)"
    val updRead = if k.name == "Ref" then "u.base.applyBoxed(ui)" else s"${k.lc}At(u.base, ui)"
    s"""  inline def dfs${k.name}(root: FBase)(inline onLeaf: (Array[${k.arr}], Int) => Unit)(inline onOne: ${k.arr} => Unit): Unit = {
       |    var stack = new Array[FBase](16); var tail = new Array[${k.arr}](16); var isTail = new Array[Boolean](16)
       |    stack(0) = root; var sp = 1
       |    while (sp > 0) {
       |      sp -= 1
       |      if (isTail(sp)) onOne(tail(sp))
       |      else stack(sp) match {
       |        case leaf: ${k.name}Arr => onLeaf(leaf.arr, leaf.length)
       |        case p: ${k.name}Prepend => { onOne(p.elem); $grow; stack(sp) = p.base; isTail(sp) = false; sp += 1 }
       |        case a: ${k.name}Append => { $grow; tail(sp) = a.elem; isTail(sp) = true; sp += 1; stack(sp) = a.base; isTail(sp) = false; sp += 1 }
       |        case c: Concat => { $grow; stack(sp) = c.right; isTail(sp) = false; sp += 1; stack(sp) = c.left; isTail(sp) = false; sp += 1 }
       |        case rev: ReverseNode => { val rn = rev.length; rev.base match { case lf: ${k.name}Arr => { val la = lf.arr; var ri = 0; while (ri < rn) { onOne(la(rn - 1 - ri)); ri += 1 } }; case _ => { var ri = 0; while (ri < rn) { onOne(${k.lc}At(rev.base, rn - 1 - ri)); ri += 1 } } } }
       |        case pad: ${k.name}Pad => { val bl = pad.base.length; pad.base match { case lf: ${k.name}Arr => { val la = lf.arr; var pi = 0; while (pi < bl) { onOne(la(pi)); pi += 1 } }; case _ => { var pi = 0; while (pi < bl) { onOne($padRead); pi += 1 } } }; val pf = pad.filler; var pj = bl; val pn = pad.length; while (pj < pn) { onOne(pf); pj += 1 } }
       |        case u: ${k.name}Updated => { val un = u.length; u.base match { case lf: ${k.name}Arr => { val la = lf.arr; var ui = 0; while (ui < un) { onOne(if (ui == u.index) u.elem else la(ui)); ui += 1 } }; case _ => { val mout = materialize${k.name}(u); onLeaf(mout, mout.length) } } }
       |        case s: SliceNode => { val sn = s.length; val so = s.offset; s.base match { case lf: ${k.name}Arr => { val la = lf.arr; var si = 0; while (si < sn) { onOne(la(so + si)); si += 1 } }; case _ => { var si = 0; while (si < sn) { onOne(${k.lc}At(s.base, so + si)); si += 1 } } } }$rngCase
       |        case _ => ()
       |      }
       |    }
       |  }""".stripMargin
  }

  private def atDef(k: Kind): String = {
    val rngCase = if k.name == "Int" then "\n       |    case rng: RangeNode => rng.start + i * rng.step" else ""
    val padBase = if k.name == "Ref" then "pad.base.applyBoxed(i)" else s"${k.lc}At(pad.base, i)"
    s"""  def ${k.lc}At(node: FBase, i: Int): ${k.arr} = node match {
       |    case leaf: ${k.name}Arr => leaf.arr(i)
       |    case c: Concat => if (i < c.left.length) ${k.lc}At(c.left, i) else ${k.lc}At(c.right, i - c.left.length)
       |    case a: ${k.name}Append => if (i < a.base.length) ${k.lc}At(a.base, i) else a.elem
       |    case p: ${k.name}Prepend => if (i == 0) p.elem else ${k.lc}At(p.base, i - 1)
       |    case rev: ReverseNode => ${k.lc}At(rev.base, rev.base.length - 1 - i)
       |    case pad: ${k.name}Pad => if (i < pad.base.length) $padBase else pad.filler
       |    case u: ${k.name}Updated => if (i == u.index) u.elem else ${if k.name == "Ref" then "u.base.applyBoxed(i)" else s"${k.lc}At(u.base, i)"}
       |    case s: SliceNode => ${k.lc}At(s.base, s.offset + i)$rngCase
       |    case _ => ${k.dflt}
       |  }""".stripMargin
  }

  private def farrayOps: String = {
    val dfs = opKinds.map(dfsDef).mkString("\n")
    val ats = opKinds.map(atDef).mkString("\n")
    // Flatten a (possibly deep) Updated chain to a fresh leaf array, ONCE, so dfs can emit it tight via
    // onLeaf instead of walking the chain per element. Recursion applies overrides bottom-up => outer wins.
    val mat = opKinds.map(k =>
      s"""  def materialize${k.name}(node: FBase): Array[${k.arr}] = node match {
         |    case u: ${k.name}Updated => { val out = materialize${k.name}(u.base); out(u.index) = u.elem; out }
         |    case _ => { val out = new Array[${k.arr}](node.length); var o = 0; dfs${k.name}(node)((a, len) => { System.arraycopy(a, 0, out, o, len); o += len })(v => { out(o) = v; o += 1 }); out }
         |  }""".stripMargin).mkString("\n")
    // Stable bottom-up mergesort directly on a kind array, ping-ponging between two buffers (no per-level
    // copy-back). `less(x, y)` = x sorts strictly before y. Returns the sorted buffer (may be the input or temp).
    // non-inline per-kind flatMap result builder: dfs+System.arraycopy each inner into one flat array (dfs
    // inlined ONCE here, not at every flatMap call site). Ref takes the ClassTag so the array is typed.
    val flatMapBuild = opKinds.map { k =>
      if k.name == "Ref" then
        s"""  def flatMapBuildRef(inners: Array[FBase], cnt: Int, total: Int, ct: scala.reflect.ClassTag[?]): Array[Object] = {
           |    val out = ct.newArray(total).asInstanceOf[Array[Object]]; var off = 0; var j = 0
           |    while (j < cnt) { dfsRef(inners(j))((a, ln) => { System.arraycopy(a, 0, out, off, ln); off += ln })(v => { out(off) = v; off += 1 }); j += 1 }
           |    out
           |  }""".stripMargin
      else
        s"""  def flatMapBuild${k.name}(inners: Array[FBase], cnt: Int, total: Int): Array[${k.arr}] = {
           |    val out = new Array[${k.arr}](total); var off = 0; var j = 0
           |    while (j < cnt) { dfs${k.name}(inners(j))((a, ln) => { System.arraycopy(a, 0, out, off, ln); off += ln })(v => { out(off) = v; off += 1 }); j += 1 }
           |    out
           |  }""".stripMargin
    }.mkString("\n")
    val sortArr = opKinds.map(k =>
      s"""  inline def sort${k.name}(a: Array[${k.arr}], n: Int)(inline less: (${k.arr}, ${k.arr}) => Boolean): Array[${k.arr}] = {
         |    var src = a; var dst = new Array[${k.arr}](n); var width = 1
         |    while (width < n) {
         |      var lo = 0
         |      while (lo < n) {
         |        val mid = if (lo + width < n) lo + width else n; val hi = if (lo + 2 * width < n) lo + 2 * width else n
         |        var i = lo; var j = mid; var k = lo
         |        while (i < mid && j < hi) { if (less(src(j), src(i))) { dst(k) = src(j); j += 1 } else { dst(k) = src(i); i += 1 }; k += 1 }
         |        while (i < mid) { dst(k) = src(i); i += 1; k += 1 }
         |        while (j < hi) { dst(k) = src(j); j += 1; k += 1 }
         |        lo += 2 * width
         |      }
         |      val t = src; src = dst; dst = t; width *= 2
         |    }
         |    src
         |  }""".stripMargin).mkString("\n")

    // Reference reads cast the leaf array to Array[A] (checkcast hoisted out of the loop at the
    // concrete inline call site; empty leaves never evaluate it). Primitive arrays can't cast to
    // Array[A] (erases to Object[]), so they read directly.
    def read(k: Kind): String = if k.name == "Ref" then "r.wrap(a.asInstanceOf[Array[A]](i))" else "r.wrap(a(i))"
    def readOne(k: Kind): String = if k.name == "Ref" then "r.wrap(v.asInstanceOf[A])" else "r.wrap(v)"
    def alloc(k: Kind, rv: String): String =
      if k.name == "Ref" then s"$rv.ct.newArray(n).asInstanceOf[Array[Object]]" else s"new Array[${k.arr}](n)"
    // a ref write stores r.Prim (= A, runtime <: Object) into an Object[] — cast it (no-op); prims store directly.
    def wr(k: Kind, e: String): String = if k.name == "Ref" then s"($e).asInstanceOf[Object]" else e
    // wrap a raw kind-array element back to A (for an inline user comparator); plain kind-array alloc
    def readVal(k: Kind, e: String): String = if k.name == "Ref" then s"r.wrap($e.asInstanceOf[A])" else s"r.wrap($e)"
    def allocPlain(k: Kind): String = s"new Array[${k.arr}](n)"
    def dispatchA(body: Kind => String): String =
      "summonFrom {\n" + opKinds.map(k => s"      case r: ${k.name}Repr[A] => ${body(k)}").mkString("\n") + "\n    }"
    def dispatchB(body: Kind => String): String =
      "summonFrom {\n" + opKinds.map(k => s"      case r: ${k.name}Repr[B] => ${body(k)}").mkString("\n") + "\n    }"

    val foldLeft = dispatchA(k =>
      s"dfs${k.name}(xs)((a, n) => { var i = 0; while (i < n) { acc = op(acc, ${read(k)}); i += 1 } })(v => { acc = op(acc, ${readOne(k)}) })")
    val foreach = dispatchA(k =>
      s"dfs${k.name}(xs)((a, n) => { var i = 0; while (i < n) { f(${read(k)}); i += 1 } })(v => { f(${readOne(k)}) })")
    // short-circuiting traversal: f returns Step.Break to stop. Leaf fast-path (tight loop + break);
    // Fused short-circuiting scan: predicate-and-break in ONE branch per element (like Array's `if (p) return`),
    // no Step round-trip. `a` = element, break via `i = ln`. Leaf fast-path (tight) + <kind>At fallback.
    def scan(k: Kind, init: String, step: String, result: String): String =
      s"xs match { case leaf: ${k.name}Arr => { val ar = leaf.arr; val ln = leaf.length; var i = 0; $init; while (i < ln) { val a = ${readVal(k, "ar(i)")}; $step }; $result }; case _ => { val ln = xs.length; var i = 0; $init; while (i < ln) { val a = ${readVal(k, s"${k.lc}At(xs, i)")}; $step }; $result } }"
    val existsV       = dispatchA(k => scan(k, "var res = false", "if (p(a)) { res = true; i = ln } else i += 1", "res"))
    val forallV       = dispatchA(k => scan(k, "var res = true", "if (p(a)) i += 1 else { res = false; i = ln }", "res"))
    val findV         = dispatchA(k => scan(k, "var res: Option[A] = None", "if (p(a)) { res = Some(a); i = ln } else i += 1", "res"))
    val indexWhereV   = dispatchA(k => scan(k, "var res = -1", "if (p(a)) { res = i; i = ln } else i += 1", "res"))
    val indexOfV      = dispatchA(k => scan(k, "var res = -1", "if (a == elem) { res = i; i = ln } else i += 1", "res"))
    val collectFirstV = dispatchA(k => scan(k, "var res: Option[B] = None", "if (pf.isDefinedAt(a)) { res = Some(pf(a)); i = ln } else i += 1", "res"))
    val prefixLenV    = dispatchA(k => scan(k, "var res = ln", "if (p(a)) i += 1 else { res = i; i = ln }", "res"))
    val mapM = "summonFrom {\n" + opKinds.map { ka =>
      val inner = "summonFrom {\n" + opKinds.map { kb =>
        s"          case rb: ${kb.name}Repr[B] => { val out = ${alloc(kb, "rb")}; var o = 0; dfs${ka.name}(xs)((a, len) => { var i = 0; while (i < len) { out(o) = ${wr(kb, s"rb.unwrap(f(${read(ka)}))")}; o += 1; i += 1 } })(v => { out(o) = ${wr(kb, s"rb.unwrap(f(${readOne(ka)}))")}; o += 1 }); new ${kb.name}Arr(out, n) }"
      }.mkString("\n") + "\n        }"
      s"      case r: ${ka.name}Repr[A] => $inner"
    }.mkString("\n") + "\n    }"
    val filter = dispatchA(k =>
      s"{ val out = ${alloc(k, "r")}; var o = 0; dfs${k.name}(xs)((a, len) => { var i = 0; while (i < len) { val e = ${read(k)}; if (p(e)) { out(o) = ${wr(k, "r.unwrap(e)")}; o += 1 }; i += 1 } })(v => { val e = ${readOne(k)}; if (p(e)) { out(o) = ${wr(k, "r.unwrap(e)")}; o += 1 } }); if (o == n) xs else if (o == 0) ${k.name}Arr.EMPTY else new ${k.name}Arr(java.util.Arrays.copyOf(out, o), o) }")
    // fused short-circuiting contains (prim compares unboxed against the unwrapped elem)
    val contains = dispatchA(k =>
      if k.name == "Ref" then s"xs match { case leaf: RefArr => { val ar = leaf.arr; val ln = leaf.length; var i = 0; var res = false; while (i < ln) { if (ar(i) == elem) { res = true; i = ln } else i += 1 }; res }; case _ => { val ln = xs.length; var i = 0; var res = false; while (i < ln) { if (refAt(xs, i) == elem) { res = true; i = ln } else i += 1 }; res } }"
      else s"{ val e = r.unwrap(elem); xs match { case leaf: ${k.name}Arr => { val ar = leaf.arr; val ln = leaf.length; var i = 0; var res = false; while (i < ln) { if (ar(i) == e) { res = true; i = ln } else i += 1 }; res }; case _ => { val ln = xs.length; var i = 0; var res = false; while (i < ln) { if (${k.lc}At(xs, i) == e) { res = true; i = ln } else i += 1 }; res } } }")
    val applyAt = dispatchA(k =>
      if k.name == "Ref" then s"r.wrap(${k.lc}At(xs, i).asInstanceOf[A])" else s"r.wrap(${k.lc}At(xs, i))")
    // flatMap result assembly dispatches only on B (4 tiny cases) and CALLS a non-inline per-kind builder,
    // so the dfs/arraycopy isn't re-inlined at every call site (keeps chained flatMap/map under the JIT's
    // HugeMethodLimit). Source is read via applyBoxed in the (kind-agnostic) impl, no dfs inlined there.
    val flatMapV = dispatchB(k =>
      if k.name == "Ref" then "if (total == 0) RefArr.EMPTY else new RefArr(flatMapBuildRef(inners, cnt, total, r.ct), total)"
      else s"if (total == 0) ${k.name}Arr.EMPTY else new ${k.name}Arr(flatMapBuild${k.name}(inners, cnt, total), total)")
    val updated = dispatchB(k => s"new ${k.name}Updated(xs, index, ${wr(k, "r.unwrap(elem)")})")
    val append = dispatchB(k => s"new ${k.name}Append(xs, r.unwrap(elem))")
    val prepend = dispatchA(k => s"new ${k.name}Prepend(r.unwrap(elem), xs)")
    val padTo = dispatchB(k => s"if (len <= xs.length) xs else new ${k.name}Pad(xs, len, ${wr(k, "r.unwrap(elem)")})")
    // Sort on FArray's own representation: materialize the kind array ONCE, stable-sort an int[] index
    // array (no Vector, no boxed indices), then permute into a fresh leaf. sortWith's comparator is inline
    // (fully unboxed); sorted/sortBy box only per ord comparison.
    // sortWith/sorted: sort the materialized kind array DIRECTLY (no index indirection).
    def sortDirect(k: Kind, less: String): String =
      s"{ val vals = materialize${k.name}(xs); val n = vals.length; if (n < 2) xs else new ${k.name}Arr(sort${k.name}(vals, n)((x, y) => $less), n) }"
    val sortWith = dispatchA(k => sortDirect(k, s"lt(${readVal(k, "x")}, ${readVal(k, "y")})"))
    val sortedV  = dispatchA(k => sortDirect(k, s"ord.lt(${readVal(k, "x")}, ${readVal(k, "y")})"))
    // sortBy: keys differ from values, so sort an int[] index by the materialized keys, then permute.
    val sortByV  = dispatchA(k => s"{ val vals = materialize${k.name}(xs); val n = vals.length; if (n < 2) xs else { val keys = mapImpl[A, B](xs)(f); val idx = new Array[Int](n); var t = 0; while (t < n) { idx(t) = t; t += 1 }; sortIndices(idx, n)((ii, jj) => ord.lt(applyAtImpl[B](keys, ii), applyAtImpl[B](keys, jj))); val out = ${allocPlain(k)}; var p = 0; while (p < n) { out(p) = vals(idx(p)); p += 1 }; new ${k.name}Arr(out, n) } }")
    val emptyB = dispatchA(k => s"${k.name}Arr.EMPTY")
    val tabulate = dispatchA(k =>
      s"if (n <= 0) ${k.name}Arr.EMPTY else { val out = ${alloc(k, "r")}; var i = 0; while (i < n) { out(i) = ${wr(k, "r.unwrap(f(i))")}; i += 1 }; new ${k.name}Arr(out, n) }")
    val applyVar = dispatchA(k =>
      s"if (as.isEmpty) ${k.name}Arr.EMPTY else { val n = as.length; val out = ${alloc(k, "r")}; var i = 0; while (i < n) { out(i) = ${wr(k, "r.unwrap(as(i))")}; i += 1 }; new ${k.name}Arr(out, n) }")
    val fromArr = dispatchA(k => s"new ${k.name}Arr(as.asInstanceOf[Array[${k.arr}]], as.length)")

    s"""package farray
       |
       |import scala.compiletime.summonFrom
       |
       |// GENERATED by GenCores — do not edit. Per-kind specialized combinator implementations.
       |object FArrayOps {
       |$dfs
       |$ats
       |$mat
       |$flatMapBuild
       |$sortArr
       |
       |  inline def emptyImpl[A]: FBase = $emptyB
       |  inline def applyImpl[A](as: Seq[A]): FBase = $applyVar
       |  inline def tabulateImpl[A](n: Int)(inline f: Int => A): FBase = $tabulate
       |  inline def fromArrayImpl[A](as: Array[A]): FBase = $fromArr
       |  inline def foldLeftImpl[A, Z](xs: FBase, z: Z)(inline op: (Z, A) => Z): Z = {
       |    var acc = z
       |    $foldLeft
       |    acc
       |  }
       |  inline def foreachImpl[A](xs: FBase)(inline f: A => Unit): Unit = $foreach
       |  inline def existsImpl[A](xs: FBase)(inline p: A => Boolean): Boolean = $existsV
       |  inline def forallImpl[A](xs: FBase)(inline p: A => Boolean): Boolean = $forallV
       |  inline def findImpl[A](xs: FBase)(inline p: A => Boolean): Option[A] = $findV
       |  inline def indexWhereImpl[A](xs: FBase)(inline p: A => Boolean): Int = $indexWhereV
       |  inline def indexOfImpl[A, B](xs: FBase, elem: B): Int = $indexOfV
       |  inline def collectFirstImpl[A, B](xs: FBase)(pf: PartialFunction[A, B]): Option[B] = $collectFirstV
       |  inline def prefixLengthImpl[A](xs: FBase)(inline p: A => Boolean): Int = $prefixLenV
       |  inline def mapImpl[A, B](xs: FBase)(inline f: A => B): FBase = {
       |    val n = xs.length
       |    $mapM
       |  }
       |  inline def filterImpl[A](xs: FBase)(inline p: A => Boolean): FBase = {
       |    val n = xs.length
       |    $filter
       |  }
       |  inline def containsImpl[A](xs: FBase, elem: A): Boolean = $contains
       |  inline def applyAtImpl[A](xs: FBase, i: Int): A = $applyAt
       |  inline def flatMapImpl[A, B](xs: FBase)(inline f: A => FBase): FBase = {
       |    val cnt = xs.length; val inners = new Array[FBase](cnt); var total = 0; var i0 = 0
       |    while (i0 < cnt) { val inr = f((xs: FBase).applyBoxed(i0).asInstanceOf[A]); inners(i0) = inr; total += inr.length; i0 += 1 }
       |    $flatMapV
       |  }
       |  inline def updatedImpl[A, B](xs: FBase, index: Int, elem: B): FBase = $updated
       |  inline def appendImpl[A, B](xs: FBase, elem: B): FBase = $append
       |  inline def prependImpl[A](elem: A, xs: FBase): FBase = $prepend
       |  inline def padToImpl[A, B](xs: FBase, len: Int, elem: B): FBase = $padTo
       |  // stable bottom-up mergesort over an int[] of indices; `less(i, j)` = element-at-i sorts before element-at-j
       |  inline def sortIndices(idx: Array[Int], n: Int)(inline less: (Int, Int) => Boolean): Unit = {
       |    val tmp = new Array[Int](n)
       |    var width = 1
       |    while (width < n) {
       |      var lo = 0
       |      while (lo < n) {
       |        val mid = if (lo + width < n) lo + width else n
       |        val hi = if (lo + 2 * width < n) lo + 2 * width else n
       |        var i = lo; var j = mid; var k = lo
       |        while (i < mid && j < hi) { if (less(idx(j), idx(i))) { tmp(k) = idx(j); j += 1 } else { tmp(k) = idx(i); i += 1 }; k += 1 }
       |        while (i < mid) { tmp(k) = idx(i); i += 1; k += 1 }
       |        while (j < hi) { tmp(k) = idx(j); j += 1; k += 1 }
       |        lo += 2 * width
       |      }
       |      System.arraycopy(tmp, 0, idx, 0, n)
       |      width *= 2
       |    }
       |  }
       |  inline def sortWithImpl[A](xs: FBase)(inline lt: (A, A) => Boolean): FBase = $sortWith
       |  inline def sortedImpl[A, B >: A](xs: FBase)(using ord: Ordering[B]): FBase = $sortedV
       |  inline def sortByImpl[A, B](xs: FBase)(inline f: A => B)(using ord: Ordering[B]): FBase = $sortByV
       |}
       |""".stripMargin
  }

  private def fbase: String = {
    val leaves = prims.flatMap(p => List(s"${p.name}Arr", s"${p.name}Append", s"${p.name}Prepend"))
    val permits = (leaves ++ List("RefArr", "RefAppend", "RefPrepend", "Concat", "RangeNode", "ReverseNode", "SliceNode") ++ padKinds.map(_._1 + "Pad") ++ padKinds.map(_._1 + "Updated")).mkString(", ")
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit.
       |public sealed abstract class FBase permits $permits {
       |    public final int length;
       |    protected FBase(int length) { this.length = length; }
       |
       |    public abstract Object applyBoxed(int i);
       |    public abstract FBase take(int n);
       |    public abstract FBase drop(int n);
       |    public abstract FBase slice(int from, int until);
       |    public abstract FBase reverse();
       |    public abstract FBase init();
       |
       |    /** O(1) concat: builds a Concat tree node; never casts, so heterogeneous kinds are safe. */
       |    public final FBase concat(FBase that) {
       |        if (that.length == 0) return this;
       |        if (this.length == 0) return that;
       |        return new Concat(this, that);
       |    }
       |}
       |""".stripMargin
  }

  private def primCore(p: Prim): String = {
    val cls = s"${p.name}Arr"
    s"""package farray;
       |
       |import java.util.Arrays;
       |
       |// GENERATED by GenCores — do not edit. ${p.jt}[]-backed specialized leaf.
       |public final class $cls extends FBase {
       |    public final ${p.jt}[] arr;
       |    public $cls(${p.jt}[] arr, int length) { super(length); this.arr = arr; }
       |    public static final $cls EMPTY = new $cls(new ${p.jt}[0], 0);
       |
       |    @Override public Object applyBoxed(int i) { return ${p.boxed}.valueOf(arr[i]); }
       |
       |    @Override public FBase take(int n) { int m = n < 0 ? 0 : (n > length ? length : n); return m == 0 ? EMPTY : (m == length ? this : new SliceNode(this, 0, m)); }
       |    @Override public FBase drop(int n) { int d = n < 0 ? 0 : (n > length ? length : n); return d == 0 ? this : (d == length ? EMPTY : new SliceNode(this, d, length - d)); }
       |    @Override public FBase slice(int from, int until) { int lo = from < 0 ? 0 : from, hi = until > length ? length : until; if (lo >= hi) return EMPTY; return (lo == 0 && hi == length) ? this : new SliceNode(this, lo, hi - lo); }
       |    @Override public FBase reverse() { return length < 2 ? this : new ReverseNode(this); }
       |    @Override public FBase init() { return new $cls(arr, length - 1); }
       |
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object obj) {
       |        if (this == obj) return true;
       |        if (!(obj instanceof $cls)) return Concat.elementwiseEquals(this, obj);
       |        $cls other = ($cls) obj;
       |        if (other.length != length) return false;
       |        for (int i = 0; i < length; i++) if (arr[i] != other.arr[i]) return false;
       |        return true;
       |    }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin
  }

  private def refArr: String =
    s"""package farray;
       |
       |import java.util.Arrays;
       |
       |// GENERATED by GenCores — do not edit. Object[]-backed leaf for reference element types.
       |public final class RefArr extends FBase {
       |    public final Object[] arr;
       |    public RefArr(Object[] arr, int length) { super(length); this.arr = arr; }
       |    public static final RefArr EMPTY = new RefArr(new Object[0], 0);
       |
       |    @Override public Object applyBoxed(int i) { return arr[i]; }
       |
       |    @Override public FBase take(int n) { int m = n < 0 ? 0 : (n > length ? length : n); return m == 0 ? EMPTY : (m == length ? this : new SliceNode(this, 0, m)); }
       |    @Override public FBase drop(int n) { int d = n < 0 ? 0 : (n > length ? length : n); return d == 0 ? this : (d == length ? EMPTY : new SliceNode(this, d, length - d)); }
       |    @Override public FBase slice(int from, int until) { int lo = from < 0 ? 0 : from, hi = until > length ? length : until; if (lo >= hi) return EMPTY; return (lo == 0 && hi == length) ? this : new SliceNode(this, lo, hi - lo); }
       |    @Override public FBase reverse() { return length < 2 ? this : new ReverseNode(this); }
       |    @Override public FBase init() { return new RefArr(arr, length - 1); }
       |
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object obj) {
       |        if (this == obj) return true;
       |        if (!(obj instanceof RefArr)) return Concat.elementwiseEquals(this, obj);
       |        RefArr other = (RefArr) obj;
       |        if (other.length != length) return false;
       |        for (int i = 0; i < length; i++) {
       |            Object x = arr[i], y = other.arr[i];
       |            if (x == null ? y != null : !x.equals(y)) return false;
       |        }
       |        return true;
       |    }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin

  private def concat: String =
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Tree node: O(1) concat, structural ops recurse (Java
       |// recursion is fine here — only the inline Scala combinators must avoid recursion to keep the
       |// element op spliced). Element traversal uses an explicit stack in the Scala combinators.
       |public final class Concat extends FBase {
       |    public final FBase left;
       |    public final FBase right;
       |    public Concat(FBase left, FBase right) {
       |        super(left.length + right.length);
       |        this.left = left;
       |        this.right = right;
       |    }
       |
       |    @Override public Object applyBoxed(int i) {
       |        return i < left.length ? left.applyBoxed(i) : right.applyBoxed(i - left.length);
       |    }
       |    @Override public FBase take(int n) {
       |        if (n <= 0) return left.take(0);
       |        if (n >= length) return this;
       |        if (n <= left.length) return left.take(n);
       |        return new Concat(left, right.take(n - left.length));
       |    }
       |    @Override public FBase drop(int n) {
       |        if (n <= 0) return this;
       |        if (n >= length) return right.drop(right.length);
       |        if (n >= left.length) return right.drop(n - left.length);
       |        return new Concat(left.drop(n), right);
       |    }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from;
       |        int hi = until > length ? length : until;
       |        if (lo >= hi) return left.take(0);
       |        return drop(lo).take(hi - lo);
       |    }
       |    @Override public FBase reverse() { return new Concat(right.reverse(), left.reverse()); }
       |    @Override public FBase init() { return take(length - 1); }

       |
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object obj) { return elementwiseEquals(this, obj); }
       |    @Override public String toString() { return render(this); }
       |
       |    /** Shared element-wise equality across any two cores (used when concrete kinds differ). */
       |    static boolean elementwiseEquals(FBase self, Object obj) {
       |        if (self == obj) return true;
       |        if (!(obj instanceof FBase)) return false;
       |        FBase other = (FBase) obj;
       |        if (other.length != self.length) return false;
       |        for (int i = 0; i < self.length; i++) {
       |            Object x = self.applyBoxed(i), y = other.applyBoxed(i);
       |            if (x == null ? y != null : !x.equals(y)) return false;
       |        }
       |        return true;
       |    }
       |    static String render(FBase self) {
       |        StringBuilder sb = new StringBuilder("FArray(");
       |        for (int i = 0; i < self.length; i++) { if (i != 0) sb.append(", "); sb.append(self.applyBoxed(i)); }
       |        return sb.append(')').toString();
       |    }
       |}
       |""".stripMargin

  /** Closed-form Int range — O(1) construct, O(1) index/take/drop/reverse, never materializes. Int kind only. */
  private def rangeNode: String =
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Lazy closed-form Int range node.
       |public final class RangeNode extends FBase {
       |    public final int start;
       |    public final int step;
       |    public RangeNode(int start, int step, int length) { super(length); this.start = start; this.step = step; }
       |    @Override public Object applyBoxed(int i) { return Integer.valueOf(start + i * step); }
       |    @Override public FBase take(int n) {
       |        int m = n < 0 ? 0 : (n > length ? length : n);
       |        return m == length ? this : (m == 0 ? IntArr.EMPTY : new RangeNode(start, step, m));
       |    }
       |    @Override public FBase drop(int n) {
       |        int d = n < 0 ? 0 : (n > length ? length : n);
       |        return d == 0 ? this : (d == length ? IntArr.EMPTY : new RangeNode(start + d * step, step, length - d));
       |    }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from, hi = until > length ? length : until;
       |        if (lo >= hi) return IntArr.EMPTY;
       |        return new RangeNode(start + lo * step, step, hi - lo);
       |    }
       |    @Override public FBase reverse() { return length < 2 ? this : new RangeNode(start + (length - 1) * step, -step, length); }
       |    @Override public FBase init() { return take(length - 1); }
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object o) { return Concat.elementwiseEquals(this, o); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin

  /** Lazy reverse — O(1) construct, shares the base; index/dfs read the base at the mirrored position. */
  private def reverseNode: String =
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Lazy reverse node (kind-agnostic; base shared).
       |public final class ReverseNode extends FBase {
       |    public final FBase base;
       |    public ReverseNode(FBase base) { super(base.length); this.base = base; }
       |    @Override public Object applyBoxed(int i) { return base.applyBoxed(length - 1 - i); }
       |    @Override public FBase take(int n) {
       |        int m = n < 0 ? 0 : (n > length ? length : n);
       |        if (m == 0) return base.take(0);
       |        return new ReverseNode(base.drop(length - m));
       |    }
       |    @Override public FBase drop(int n) {
       |        int d = n < 0 ? 0 : (n > length ? length : n);
       |        if (d == length) return base.take(0);
       |        return new ReverseNode(base.take(length - d));
       |    }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from, hi = until > length ? length : until;
       |        if (lo >= hi) return base.take(0);
       |        return drop(lo).take(hi - lo);
       |    }
       |    @Override public FBase reverse() { return base; }
       |    @Override public FBase init() { return take(length - 1); }
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object o) { return Concat.elementwiseEquals(this, o); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin

  /** Lazy slice — O(1) take/drop/slice as a window (base + offset) into the base; index reads base at offset+i. */
  private def sliceNode: String =
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Lazy slice/take/drop node (kind-agnostic window over a leaf base).
       |public final class SliceNode extends FBase {
       |    public final FBase base;
       |    public final int offset;
       |    public SliceNode(FBase base, int offset, int length) { super(length); this.base = base; this.offset = offset; }
       |    @Override public Object applyBoxed(int i) { return base.applyBoxed(offset + i); }
       |    @Override public FBase take(int n) { int m = n < 0 ? 0 : (n > length ? length : n); return m == length ? this : new SliceNode(base, offset, m); }
       |    @Override public FBase drop(int n) { int d = n < 0 ? 0 : (n > length ? length : n); return d == 0 ? this : new SliceNode(base, offset + d, length - d); }
       |    @Override public FBase slice(int from, int until) { int lo = from < 0 ? 0 : from, hi = until > length ? length : until; if (lo >= hi) return new SliceNode(base, offset, 0); return (lo == 0 && hi == length) ? this : new SliceNode(base, offset + lo, hi - lo); }
       |    @Override public FBase reverse() { return new ReverseNode(this); }
       |    @Override public FBase init() { return take(length - 1); }
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object o) { return Concat.elementwiseEquals(this, o); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin

  /** Ops-kinds (Int/Long/Double/Ref) for the per-kind lazy nodes that carry a primitive payload. */
  private val padKinds = List(("Int", "int", "Integer"), ("Long", "long", "Long"), ("Double", "double", "Double"), ("Ref", "Object", ""))

  /** padTo as a lazy node: base + targetLen + a constant filler. O(1) construct, O(depth) index — so
    * range(1M).padTo(2M, x).last is O(1). For prims base is always the same kind (B>:A, prims are final);
    * RefPad reads its base via applyBoxed so an Int-base widened to a Ref pad still works. */
  private def padNode(name: String, jt: String, boxed: String): String =
    val boxedFiller = if boxed.isEmpty then "filler" else s"$boxed.valueOf(filler)"
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Lazy padTo node (base shared, constant filler).
       |public final class ${name}Pad extends FBase {
       |    public final FBase base;
       |    public final $jt filler;
       |    public ${name}Pad(FBase base, int targetLen, $jt filler) { super(targetLen); this.base = base; this.filler = filler; }
       |    @Override public Object applyBoxed(int i) { return i < base.length ? base.applyBoxed(i) : $boxedFiller; }
       |    @Override public FBase take(int n) { int m = n < 0 ? 0 : (n > length ? length : n); return m <= base.length ? base.take(m) : new ${name}Pad(base, m, filler); }
       |    @Override public FBase drop(int n) {
       |        int d = n < 0 ? 0 : (n > length ? length : n);
       |        if (d == 0) return this;
       |        if (d >= length) return base.take(0);
       |        if (d >= base.length) return new ${name}Pad(base.take(0), length - d, filler);
       |        return new ${name}Pad(base.drop(d), length - d, filler);
       |    }
       |    @Override public FBase slice(int from, int until) { int lo = from < 0 ? 0 : from, hi = until > length ? length : until; return lo >= hi ? base.take(0) : drop(lo).take(hi - lo); }
       |    @Override public FBase reverse() { return new ReverseNode(this); }
       |    @Override public FBase init() { return take(length - 1); }
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object o) { return Concat.elementwiseEquals(this, o); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin

  /** updated as a lazy node: base + a single overridden (index, elem). O(1) construct, O(depth) index. */
  private def updatedNode(name: String, jt: String, boxed: String): String =
    val boxedElem = if boxed.isEmpty then "elem" else s"$boxed.valueOf(elem)"
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Lazy updated node (base shared, one overridden element).
       |public final class ${name}Updated extends FBase {
       |    public final FBase base;
       |    public final int index;
       |    public final $jt elem;
       |    public ${name}Updated(FBase base, int index, $jt elem) { super(base.length); this.base = base; this.index = index; this.elem = elem; }
       |    @Override public Object applyBoxed(int i) { return i == index ? $boxedElem : base.applyBoxed(i); }
       |    @Override public FBase take(int n) { int m = n < 0 ? 0 : (n > length ? length : n); return m <= index ? base.take(m) : new ${name}Updated(base.take(m), index, elem); }
       |    @Override public FBase drop(int n) { int d = n < 0 ? 0 : (n > length ? length : n); return d > index ? base.drop(d) : new ${name}Updated(base.drop(d), index - d, elem); }
       |    @Override public FBase slice(int from, int until) { int lo = from < 0 ? 0 : from, hi = until > length ? length : until; return lo >= hi ? base.take(0) : drop(lo).take(hi - lo); }
       |    @Override public FBase reverse() { return new ReverseNode(this); }
       |    @Override public FBase init() { return take(length - 1); }
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object o) { return Concat.elementwiseEquals(this, o); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin

  /** Unboxed, order-dependent hash: dispatch on each node's runtime kind and hash raw primitives.
    * Replaces the per-node applyBoxed loops (which boxed every element). `rev` flips order for ReverseNode. */
  private def hashing: String = {
    def eh(p: Prim, e: String): String = p.name match
      case "Long"    => s"scala.runtime.Statics.longHash($e)"
      case "Double"  => s"scala.runtime.Statics.doubleHash($e)"
      case "Float"   => s"scala.runtime.Statics.floatHash($e)"
      case "Boolean" => s"($e ? 1231 : 1237)"
      case _         => e // Int/Short/Byte/Char: ## is the (widened) value
    val leafFill = prims.map(p =>
      s"""       |        if (node instanceof ${p.name}Arr a) { if (rev) for (int i = a.length - 1; i >= 0; i--) hs[pos++] = ${eh(p, "a.arr[i]")}; else for (int i = 0; i < a.length; i++) hs[pos++] = ${eh(p, "a.arr[i]")}; return pos; }""").mkString("\n")
    val appendFill = prims.map(p =>
      s"""       |        if (node instanceof ${p.name}Append ap) { if (rev) { hs[pos++] = ${eh(p, "ap.elem")}; return fill(ap.base, true, hs, pos); } else { pos = fill(ap.base, false, hs, pos); hs[pos++] = ${eh(p, "ap.elem")}; return pos; } }""").mkString("\n")
    val prependFill = prims.map(p =>
      s"""       |        if (node instanceof ${p.name}Prepend pp) { if (rev) { pos = fill(pp.base, true, hs, pos); hs[pos++] = ${eh(p, "pp.elem")}; return pos; } else { hs[pos++] = ${eh(p, "pp.elem")}; return fill(pp.base, false, hs, pos); } }""").mkString("\n")
    val padFill = padKinds.map { case (name, _, _) =>
      val fh = name match
        case "Long"   => "scala.runtime.Statics.longHash(pad.filler)"
        case "Double" => "scala.runtime.Statics.doubleHash(pad.filler)"
        case "Ref"    => "scala.runtime.Statics.anyHash(pad.filler)"
        case _        => "pad.filler"
      s"""       |        if (node instanceof ${name}Pad pad) { int extra = pad.length - pad.base.length; if (rev) { for (int i = 0; i < extra; i++) hs[pos++] = $fh; return fill(pad.base, true, hs, pos); } else { pos = fill(pad.base, false, hs, pos); for (int i = 0; i < extra; i++) hs[pos++] = $fh; return pos; } }"""
    }.mkString("\n")
    val updatedFill = padKinds.map { case (name, _, _) =>
      val eh2 = name match
        case "Long"   => "scala.runtime.Statics.longHash(u.elem)"
        case "Double" => "scala.runtime.Statics.doubleHash(u.elem)"
        case "Ref"    => "scala.runtime.Statics.anyHash(u.elem)"
        case _        => "u.elem"
      s"""       |        if (node instanceof ${name}Updated u) { int start = pos; pos = fill(u.base, rev, hs, pos); hs[rev ? (start + u.length - 1 - u.index) : (start + u.index)] = $eh2; return pos; }"""
    }.mkString("\n")
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Hash byte-for-byte equal to Scala Seq.hashCode (List/Vector):
       |// collect each element's ## (unboxed, via scala.runtime.Statics) into an int[], then run MurmurHash3's
       |// ordered hash INCLUDING its arithmetic-progression optimisation (a constant-stride hash sequence ->
       |// rangeHash). A standalone RangeNode hashes in O(1) via rangeHash (no million-element walk). The int[]
       |// holds primitive element-hashes — no element is ever boxed.
       |final class Hashing {
       |    private static final int SEED = "Seq".hashCode();
       |    static int hashOf(FBase node) {
       |        if (node instanceof RangeNode rg) {
       |            if (rg.length == 0) return finalizeHash(SEED, 0);
       |            if (rg.length == 1) return finalizeHash(mix(SEED, rg.start), 1);
       |            return rangeHash(rg.start, rg.step, rg.start + (rg.length - 1) * rg.step, SEED);
       |        }
       |        int[] hs = new int[node.length];
       |        fill(node, false, hs, 0);
       |        return ordered(hs);
       |    }
       |    private static int mix(int h, int d) { return scala.util.hashing.MurmurHash3$$.MODULE$$.mix(h, d); }
       |    private static int finalizeHash(int h, int n) { return scala.util.hashing.MurmurHash3$$.MODULE$$.finalizeHash(h, n); }
       |    private static int rangeHash(int start, int step, int last, int seed) { return scala.util.hashing.MurmurHash3$$.MODULE$$.rangeHash(start, step, last, seed); }
       |    /** Exactly scala.util.hashing.MurmurHash3.orderedHash, hoisted to an int[] of element-hashes. */
       |    private static int ordered(int[] h) {
       |        int n = h.length;
       |        if (n == 0) return finalizeHash(SEED, 0);
       |        if (n == 1) return finalizeHash(mix(SEED, h[0]), 1);
       |        int diff = h[1] - h[0];
       |        boolean isRange = true;
       |        for (int i = 2; i < n; i++) if (h[i] - h[i - 1] != diff) { isRange = false; break; }
       |        if (isRange) return rangeHash(h[0], diff, h[n - 1], SEED);
       |        int acc = SEED;
       |        for (int i = 0; i < n; i++) acc = mix(acc, h[i]);
       |        return finalizeHash(acc, n);
       |    }
       |    /** Append each element's ## to hs in sequence order (rev flips it); returns the next free index. */
       |    private static int fill(FBase node, boolean rev, int[] hs, int pos) {
$leafFill
       |        if (node instanceof RefArr a) { if (rev) for (int i = a.length - 1; i >= 0; i--) hs[pos++] = scala.runtime.Statics.anyHash(a.arr[i]); else for (int i = 0; i < a.length; i++) hs[pos++] = scala.runtime.Statics.anyHash(a.arr[i]); return pos; }
       |        if (node instanceof Concat c) { if (rev) { pos = fill(c.right, true, hs, pos); return fill(c.left, true, hs, pos); } else { pos = fill(c.left, false, hs, pos); return fill(c.right, false, hs, pos); } }
$appendFill
$prependFill
       |        if (node instanceof RefAppend ap) { if (rev) { hs[pos++] = scala.runtime.Statics.anyHash(ap.elem); return fill(ap.base, true, hs, pos); } else { pos = fill(ap.base, false, hs, pos); hs[pos++] = scala.runtime.Statics.anyHash(ap.elem); return pos; } }
       |        if (node instanceof RefPrepend pp) { if (rev) { pos = fill(pp.base, true, hs, pos); hs[pos++] = scala.runtime.Statics.anyHash(pp.elem); return pos; } else { hs[pos++] = scala.runtime.Statics.anyHash(pp.elem); return fill(pp.base, false, hs, pos); } }
       |        if (node instanceof ReverseNode r) { return fill(r.base, !rev, hs, pos); }
       |        if (node instanceof SliceNode s) { int[] tmp = new int[s.base.length]; fill(s.base, false, tmp, 0); if (rev) for (int i = s.length - 1; i >= 0; i--) hs[pos++] = tmp[s.offset + i]; else for (int i = 0; i < s.length; i++) hs[pos++] = tmp[s.offset + i]; return pos; }
$padFill
$updatedFill
       |        if (node instanceof RangeNode rg) { if (rev) for (int i = rg.length - 1; i >= 0; i--) hs[pos++] = rg.start + i * rg.step; else for (int i = 0; i < rg.length; i++) hs[pos++] = rg.start + i * rg.step; return pos; }
       |        for (int i = 0; i < node.length; i++) hs[pos++] = scala.runtime.Statics.anyHash(node.applyBoxed(rev ? node.length - 1 - i : i));
       |        return pos;
       |    }
       |}
       |""".stripMargin
  }

  private def primAppend(p: Prim): String = {
    val cls = s"${p.name}Append"
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Unary append node (base + one ${p.jt}, base shared).
       |public final class $cls extends FBase {
       |    public final FBase base;
       |    public final ${p.jt} elem;
       |    public $cls(FBase base, ${p.jt} elem) { super(base.length + 1); this.base = base; this.elem = elem; }
       |    @Override public Object applyBoxed(int i) { return i < base.length ? base.applyBoxed(i) : ${p.boxed}.valueOf(elem); }
       |    @Override public FBase take(int n) { return n >= length ? this : base.take(n); }
       |    @Override public FBase drop(int n) {
       |        if (n <= 0) return this;
       |        if (n >= length) return base.take(0);
       |        return new $cls(base.drop(n), elem);
       |    }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from; int hi = until > length ? length : until;
       |        if (lo >= hi) return base.take(0);
       |        return drop(lo).take(hi - lo);
       |    }
       |    @Override public FBase reverse() { return new ${p.name}Prepend(elem, base.reverse()); }
       |    @Override public FBase init() { return base; }
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object obj) { return Concat.elementwiseEquals(this, obj); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin
  }

  private def primPrepend(p: Prim): String = {
    val cls = s"${p.name}Prepend"
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Unary prepend node (one ${p.jt} + base, base shared).
       |public final class $cls extends FBase {
       |    public final ${p.jt} elem;
       |    public final FBase base;
       |    public $cls(${p.jt} elem, FBase base) { super(base.length + 1); this.elem = elem; this.base = base; }
       |    @Override public Object applyBoxed(int i) { return i == 0 ? ${p.boxed}.valueOf(elem) : base.applyBoxed(i - 1); }
       |    @Override public FBase take(int n) {
       |        if (n <= 0) return base.take(0);
       |        if (n >= length) return this;
       |        return new $cls(elem, base.take(n - 1));
       |    }
       |    @Override public FBase drop(int n) {
       |        if (n <= 0) return this;
       |        if (n >= length) return base.take(0);
       |        return base.drop(n - 1);
       |    }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from; int hi = until > length ? length : until;
       |        if (lo >= hi) return base.take(0);
       |        return drop(lo).take(hi - lo);
       |    }
       |    @Override public FBase reverse() { return new ${p.name}Append(base.reverse(), elem); }
       |    @Override public FBase init() { return take(length - 1); }
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object obj) { return Concat.elementwiseEquals(this, obj); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin
  }

  private def refUnary(kind: String): String = {
    val cls = s"Ref$kind"
    val isAppend = kind == "Append"
    val fields = if isAppend then "public final FBase base;\n    public final Object elem;"
                 else "public final Object elem;\n    public final FBase base;"
    val ctorArgs = if isAppend then "FBase base, Object elem" else "Object elem, FBase base"
    val ctorBody = if isAppend then "this.base = base; this.elem = elem;" else "this.elem = elem; this.base = base;"
    val applyB = if isAppend then "i < base.length ? base.applyBoxed(i) : elem" else "i == 0 ? elem : base.applyBoxed(i - 1)"
    val take = if isAppend then "return n >= length ? this : base.take(n);"
               else "if (n <= 0) return base.take(0); if (n >= length) return this; return new RefPrepend(elem, base.take(n - 1));"
    val drop = if isAppend then "if (n <= 0) return this; if (n >= length) return base.take(0); return new RefAppend(base.drop(n), elem);"
               else "if (n <= 0) return this; if (n >= length) return base.take(0); return base.drop(n - 1);"
    val reverse = if isAppend then "return new RefPrepend(elem, base.reverse());" else "return new RefAppend(base.reverse(), elem);"
    val init = if isAppend then "return base;" else "return take(length - 1);"
    s"""package farray;
       |
       |// GENERATED by GenCores — do not edit. Unary $kind node for reference elements (base shared).
       |public final class $cls extends FBase {
       |    $fields
       |    public $cls($ctorArgs) { super(base.length + 1); $ctorBody }
       |    @Override public Object applyBoxed(int i) { return $applyB; }
       |    @Override public FBase take(int n) { $take }
       |    @Override public FBase drop(int n) { $drop }
       |    @Override public FBase slice(int from, int until) {
       |        int lo = from < 0 ? 0 : from; int hi = until > length ? length : until;
       |        if (lo >= hi) return base.take(0);
       |        return drop(lo).take(hi - lo);
       |    }
       |    @Override public FBase reverse() { $reverse }
       |    @Override public FBase init() { $init }
       |    @Override public int hashCode() { return Hashing.hashOf(this); }
       |    @Override public boolean equals(Object obj) { return Concat.elementwiseEquals(this, obj); }
       |    @Override public String toString() { return Concat.render(this); }
       |}
       |""".stripMargin
  }
}
