name: Build
on:
  push:
    tags: [ 'v*' ]
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    timeout-minutes: 15
    # need to be newer than `ubuntu-20.04` because of scalafmt native binary
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: bleep-build/bleep-setup-action@0.0.1
      - uses: coursier/cache-action@v6
        with:
          extraFiles: bleep.yaml

      - name: Scalafmt Check
        run: bleep fmt --check

      - name: Run tests
        env:
          CI: true
        run: |
          bleep compile
          bleep test

  release:
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    needs: [ build ]
    if: "startsWith(github.ref, 'refs/tags/v')"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - id: get_version
        uses: battila7/get-version-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          path: artifacts
      - name: Display structure of downloaded files
        run: find artifacts
      - name: Release
        run: bleep publish
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      - name: Upload-to-release
        uses: softprops/action-gh-release@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          name: "${{ steps.get_version.outputs.version-without-v }}"
          prerelease: true
          generate_release_notes: true
